<!-- Device group small template -->
<script type="text/x-kendo-tmpl" id="devicegroup-entry-small">
	<div class="asset-entry gradient-bg" id="group-#:token#">
		<div class="asset-entry-logowrapper">
			<img class="asset-entry-logo" src="${pageContext.request.contextPath}/img/devicegroup.png"/>
		</div>
		<div class="ellipsis"><b>#:name#</b></div>
		<div class="ellipsis">#:description#)</div>
	</div>
</script>