		</div>
		<div style="height: 10px;"></div>
		<div class="sw-footer">
			<span style="position: absolute; right: 10px; color: #999;">
				${version.versionIdentifier}.${version.buildTimestamp} (${version.editionIdentifier})
			</span>
			Copyright © 2009-2015 SiteWhere, LLC.
		</div>
	</div>
<script src="${pageContext.request.contextPath}/scripts/bootstrap.min.js"></script>
</body>
</html>