
package com.sitewhere.wso2.identity.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Aug 05 14:07:18 EDT 2015
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "RemoteUserStoreManagerServiceUserStoreException", targetNamespace = "http://service.ws.um.carbon.wso2.org")
public class RemoteUserStoreManagerServiceUserStoreException_Exception extends Exception {
    public static final long serialVersionUID = 20150805140718L;
    
    private com.sitewhere.wso2.identity.ws.RemoteUserStoreManagerServiceUserStoreException remoteUserStoreManagerServiceUserStoreException;

    public RemoteUserStoreManagerServiceUserStoreException_Exception() {
        super();
    }
    
    public RemoteUserStoreManagerServiceUserStoreException_Exception(String message) {
        super(message);
    }
    
    public RemoteUserStoreManagerServiceUserStoreException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RemoteUserStoreManagerServiceUserStoreException_Exception(String message, com.sitewhere.wso2.identity.ws.RemoteUserStoreManagerServiceUserStoreException remoteUserStoreManagerServiceUserStoreException) {
        super(message);
        this.remoteUserStoreManagerServiceUserStoreException = remoteUserStoreManagerServiceUserStoreException;
    }

    public RemoteUserStoreManagerServiceUserStoreException_Exception(String message, com.sitewhere.wso2.identity.ws.RemoteUserStoreManagerServiceUserStoreException remoteUserStoreManagerServiceUserStoreException, Throwable cause) {
        super(message, cause);
        this.remoteUserStoreManagerServiceUserStoreException = remoteUserStoreManagerServiceUserStoreException;
    }

    public com.sitewhere.wso2.identity.ws.RemoteUserStoreManagerServiceUserStoreException getFaultInfo() {
        return this.remoteUserStoreManagerServiceUserStoreException;
    }
}
