package com.sitewhere.assetmodule.magento.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1
 * Fri Oct 18 03:30:17 EDT 2013
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "urn:Magento", name = "Mage_Api_Model_Server_Wsi_HandlerPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MageApiModelServerWsiHandlerPortType {

    @WebResult(name = "catalogProductAttributeInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeInfoResponseParam catalogProductAttributeInfo(
        @WebParam(partName = "parameters", name = "catalogProductAttributeInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeInfoRequestParam parameters
    );

    @WebResult(name = "catalogProductDeleteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductDeleteResponseParam catalogProductDelete(
        @WebParam(partName = "parameters", name = "catalogProductDeleteRequestParam", targetNamespace = "urn:Magento")
        CatalogProductDeleteRequestParam parameters
    );

    @WebResult(name = "catalogProductDownloadableLinkAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductDownloadableLinkAddResponseParam catalogProductDownloadableLinkAdd(
        @WebParam(partName = "parameters", name = "catalogProductDownloadableLinkAddRequestParam", targetNamespace = "urn:Magento")
        CatalogProductDownloadableLinkAddRequestParam parameters
    );

    @WebResult(name = "salesOrderCreditmemoListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderCreditmemoListResponseParam salesOrderCreditmemoList(
        @WebParam(partName = "parameters", name = "salesOrderCreditmemoListRequestParam", targetNamespace = "urn:Magento")
        SalesOrderCreditmemoListRequestParam parameters
    );

    @WebResult(name = "catalogProductCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCreateResponseParam catalogProductCreate(
        @WebParam(partName = "parameters", name = "catalogProductCreateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCreateRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeCurrentStoreResponseParam catalogProductAttributeCurrentStore(
        @WebParam(partName = "parameters", name = "catalogProductAttributeCurrentStoreRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeCurrentStoreRequestParam parameters
    );

    @WebResult(name = "catalogProductCustomOptionValueListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCustomOptionValueListResponseParam catalogProductCustomOptionValueList(
        @WebParam(partName = "parameters", name = "catalogProductCustomOptionValueListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCustomOptionValueListRequestParam parameters
    );

    @WebResult(name = "catalogCategoryAttributeCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryAttributeCurrentStoreResponseParam catalogCategoryAttributeCurrentStore(
        @WebParam(partName = "parameters", name = "catalogCategoryAttributeCurrentStoreRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryAttributeCurrentStoreRequestParam parameters
    );

    @WebResult(name = "salesOrderCancelResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderCancelResponseParam salesOrderCancel(
        @WebParam(partName = "parameters", name = "salesOrderCancelRequestParam", targetNamespace = "urn:Magento")
        SalesOrderCancelRequestParam parameters
    );

    @WebResult(name = "resourceFaultsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ResourceFaultsResponseParam resourceFaults(
        @WebParam(partName = "parameters", name = "resourceFaultsParam", targetNamespace = "urn:Magento")
        ResourceFaultsParam parameters
    );

    @WebResult(name = "giftMessageForQuoteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftMessageForQuoteResponseParam giftMessageSetForQuote(
        @WebParam(partName = "parameters", name = "giftMessageForQuoteRequestParam", targetNamespace = "urn:Magento")
        GiftMessageForQuoteRequestParam parameters
    );

    @WebResult(name = "catalogProductTypeListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductTypeListResponseParam catalogProductTypeList(
        @WebParam(partName = "parameters", name = "catalogProductTypeListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductTypeListRequestParam parameters
    );

    @WebResult(name = "multiCallResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public MultiCallResponseParam multiCall(
        @WebParam(partName = "parameters", name = "multiCallParam", targetNamespace = "urn:Magento")
        MultiCallParam parameters
    );

    @WebResult(name = "catalogProductLinkListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductLinkListResponseParam catalogProductLinkList(
        @WebParam(partName = "parameters", name = "catalogProductLinkListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductLinkListRequestParam parameters
    );

    @WebResult(name = "salesOrderShipmentGetCarriersResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentGetCarriersResponseParam salesOrderShipmentGetCarriers(
        @WebParam(partName = "parameters", name = "salesOrderShipmentGetCarriersRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentGetCarriersRequestParam parameters
    );

    @WebResult(name = "catalogCategoryRemoveProductResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryRemoveProductResponseParam catalogCategoryRemoveProduct(
        @WebParam(partName = "parameters", name = "catalogCategoryRemoveProductRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryRemoveProductRequestParam parameters
    );

    @WebResult(name = "salesOrderShipmentCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentCreateResponseParam salesOrderShipmentCreate(
        @WebParam(partName = "parameters", name = "salesOrderShipmentCreateRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentCreateRequestParam parameters
    );

    @WebResult(name = "salesOrderInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInfoResponseParam salesOrderInfo(
        @WebParam(partName = "parameters", name = "salesOrderInfoRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInfoRequestParam parameters
    );

    @WebResult(name = "catalogProductLinkUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductLinkUpdateResponseParam catalogProductLinkUpdate(
        @WebParam(partName = "parameters", name = "catalogProductLinkUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductLinkUpdateRequestParam parameters
    );

    @WebResult(name = "shoppingCartProductUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartProductUpdateResponseParam shoppingCartProductUpdate(
        @WebParam(partName = "parameters", name = "shoppingCartProductUpdateRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartProductUpdateRequestParam parameters
    );

    @WebResult(name = "catalogCategoryCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryCurrentStoreResponseParam catalogCategoryCurrentStore(
        @WebParam(partName = "parameters", name = "catalogCategoryCurrentStoreRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryCurrentStoreRequestParam parameters
    );

    @WebResult(name = "customerAddressCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerAddressCreateResponseParam customerAddressCreate(
        @WebParam(partName = "parameters", name = "customerAddressCreateRequestParam", targetNamespace = "urn:Magento")
        CustomerAddressCreateRequestParam parameters
    );

    @WebResult(name = "catalogCategoryAttributeOptionsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryAttributeOptionsResponseParam catalogCategoryAttributeOptions(
        @WebParam(partName = "parameters", name = "catalogCategoryAttributeOptionsRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryAttributeOptionsRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeSetRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeSetRemoveResponseParam catalogProductAttributeSetRemove(
        @WebParam(partName = "parameters", name = "catalogProductAttributeSetRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeSetRemoveRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeOptionsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeOptionsResponseParam catalogProductAttributeOptions(
        @WebParam(partName = "parameters", name = "catalogProductAttributeOptionsRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeOptionsRequestParam parameters
    );

    @WebResult(name = "salesOrderCreditmemoInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderCreditmemoInfoResponseParam salesOrderCreditmemoInfo(
        @WebParam(partName = "parameters", name = "salesOrderCreditmemoInfoRequestParam", targetNamespace = "urn:Magento")
        SalesOrderCreditmemoInfoRequestParam parameters
    );

    @WebResult(name = "salesOrderShipmentInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentInfoResponseParam salesOrderShipmentInfo(
        @WebParam(partName = "parameters", name = "salesOrderShipmentInfoRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentInfoRequestParam parameters
    );

    @WebResult(name = "globalFaultsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GlobalFaultsResponseParam globalFaults(
        @WebParam(partName = "parameters", name = "globalFaultsParam", targetNamespace = "urn:Magento")
        GlobalFaultsParam parameters
    );

    @WebResult(name = "shoppingCartShippingMethodResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartShippingMethodResponseParam shoppingCartShippingMethod(
        @WebParam(partName = "parameters", name = "shoppingCartShippingMethodRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartShippingMethodRequestParam parameters
    );

    @WebResult(name = "catalogCategoryUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryUpdateResponseParam catalogCategoryUpdate(
        @WebParam(partName = "parameters", name = "catalogCategoryUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryUpdateRequestParam parameters
    );

    @WebResult(name = "catalogCategoryDeleteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryDeleteResponseParam catalogCategoryDelete(
        @WebParam(partName = "parameters", name = "catalogCategoryDeleteRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryDeleteRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeMediaCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaCreateResponseParam catalogProductAttributeMediaCreate(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaCreateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaCreateRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeUpdateResponseParam catalogProductAttributeUpdate(
        @WebParam(partName = "parameters", name = "catalogProductAttributeUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeUpdateRequestParam parameters
    );

    @WebResult(name = "catalogInventoryStockItemListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogInventoryStockItemListResponseParam catalogInventoryStockItemList(
        @WebParam(partName = "parameters", name = "catalogInventoryStockItemListRequestParam", targetNamespace = "urn:Magento")
        CatalogInventoryStockItemListRequestParam parameters
    );

    @WebResult(name = "shoppingCartCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartCreateResponseParam shoppingCartCreate(
        @WebParam(partName = "parameters", name = "shoppingCartCreateRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartCreateRequestParam parameters
    );

    @WebResult(name = "catalogProductDownloadableLinkListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductDownloadableLinkListResponseParam catalogProductDownloadableLinkList(
        @WebParam(partName = "parameters", name = "catalogProductDownloadableLinkListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductDownloadableLinkListRequestParam parameters
    );

    @WebResult(name = "storeInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public StoreInfoResponseParam storeInfo(
        @WebParam(partName = "parameters", name = "storeInfoRequestParam", targetNamespace = "urn:Magento")
        StoreInfoRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeMediaTypesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaTypesResponseParam catalogProductAttributeMediaTypes(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaTypesRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaTypesRequestParam parameters
    );

    @WebResult(name = "customerCustomerListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerCustomerListResponseParam customerCustomerList(
        @WebParam(partName = "parameters", name = "customerCustomerListRequestParam", targetNamespace = "urn:Magento")
        CustomerCustomerListRequestParam parameters
    );

    @WebResult(name = "directoryCountryListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public DirectoryCountryListResponseParam directoryCountryList(
        @WebParam(partName = "parameters", name = "directoryCountryListRequestParam", targetNamespace = "urn:Magento")
        DirectoryCountryListRequestParam parameters
    );

    @WebResult(name = "storeListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public StoreListResponseParam storeList(
        @WebParam(partName = "parameters", name = "storeListRequestParam", targetNamespace = "urn:Magento")
        StoreListRequestParam parameters
    );

    @WebResult(name = "salesOrderInvoiceInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceInfoResponseParam salesOrderInvoiceInfo(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceInfoRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceInfoRequestParam parameters
    );

    @WebResult(name = "catalogInventoryStockItemMultiUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogInventoryStockItemMultiUpdateResponseParam catalogInventoryStockItemMultiUpdate(
        @WebParam(partName = "parameters", name = "catalogInventoryStockItemMultiUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogInventoryStockItemMultiUpdateRequestParam parameters
    );

    @WebResult(name = "catalogProductCustomOptionValueUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCustomOptionValueUpdateResponseParam catalogProductCustomOptionValueUpdate(
        @WebParam(partName = "parameters", name = "catalogProductCustomOptionValueUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCustomOptionValueUpdateRequestParam parameters
    );

    @WebResult(name = "catalogProductTagRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductTagRemoveResponseParam catalogProductTagRemove(
        @WebParam(partName = "parameters", name = "catalogProductTagRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductTagRemoveRequestParam parameters
    );

    @WebResult(name = "customerAddressDeleteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerAddressDeleteResponseParam customerAddressDelete(
        @WebParam(partName = "parameters", name = "customerAddressDeleteRequestParam", targetNamespace = "urn:Magento")
        CustomerAddressDeleteRequestParam parameters
    );

    @WebResult(name = "startSessionResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public StartSessionResponseParam startSession();

    @WebResult(name = "salesOrderListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderListResponseParam salesOrderList(
        @WebParam(partName = "parameters", name = "salesOrderListRequestParam", targetNamespace = "urn:Magento")
        SalesOrderListRequestParam parameters
    );

    @WebResult(name = "catalogProductCustomOptionValueAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCustomOptionValueAddResponseParam catalogProductCustomOptionValueAdd(
        @WebParam(partName = "parameters", name = "catalogProductCustomOptionValueAddRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCustomOptionValueAddRequestParam parameters
    );

    @WebResult(name = "catalogCategoryUpdateProductResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryUpdateProductResponseParam catalogCategoryUpdateProduct(
        @WebParam(partName = "parameters", name = "catalogCategoryUpdateProductRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryUpdateProductRequestParam parameters
    );

    @WebResult(name = "shoppingCartCustomerSetResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartCustomerSetResponseParam shoppingCartCustomerSet(
        @WebParam(partName = "parameters", name = "shoppingCartCustomerSetRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartCustomerSetRequestParam parameters
    );

    @WebResult(name = "salesOrderShipmentRemoveTrackResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentRemoveTrackResponseParam salesOrderShipmentRemoveTrack(
        @WebParam(partName = "parameters", name = "salesOrderShipmentRemoveTrackRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentRemoveTrackRequestParam parameters
    );

    @WebResult(name = "catalogCategoryTreeResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryTreeResponseParam catalogCategoryTree(
        @WebParam(partName = "parameters", name = "catalogCategoryTreeRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryTreeRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeListResponseParam catalogProductAttributeList(
        @WebParam(partName = "parameters", name = "catalogProductAttributeListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeListRequestParam parameters
    );

    @WebResult(name = "catalogProductLinkAssignResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductLinkAssignResponseParam catalogProductLinkAssign(
        @WebParam(partName = "parameters", name = "catalogProductLinkAssignRequestParam", targetNamespace = "urn:Magento")
        CatalogProductLinkAssignRequestParam parameters
    );

    @WebResult(name = "catalogCategoryAssignProductResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryAssignProductResponseParam catalogCategoryAssignProduct(
        @WebParam(partName = "parameters", name = "catalogCategoryAssignProductRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryAssignProductRequestParam parameters
    );

    @WebResult(name = "catalogCategoryCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryCreateResponseParam catalogCategoryCreate(
        @WebParam(partName = "parameters", name = "catalogCategoryCreateRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryCreateRequestParam parameters
    );

    @WebResult(name = "shoppingCartOrderResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartOrderResponseParam shoppingCartOrder(
        @WebParam(partName = "parameters", name = "shoppingCartOrderRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartOrderRequestParam parameters
    );

    @WebResult(name = "catalogProductCustomOptionUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCustomOptionUpdateResponseParam catalogProductCustomOptionUpdate(
        @WebParam(partName = "parameters", name = "catalogProductCustomOptionUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCustomOptionUpdateRequestParam parameters
    );

    @WebResult(name = "catalogProductCustomOptionListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCustomOptionListResponseParam catalogProductCustomOptionList(
        @WebParam(partName = "parameters", name = "catalogProductCustomOptionListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCustomOptionListRequestParam parameters
    );

    @WebResult(name = "customerAddressUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerAddressUpdateResponseParam customerAddressUpdate(
        @WebParam(partName = "parameters", name = "customerAddressUpdateRequestParam", targetNamespace = "urn:Magento")
        CustomerAddressUpdateRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeSetGroupRenameResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeSetGroupRenameResponseParam catalogProductAttributeSetGroupRename(
        @WebParam(partName = "parameters", name = "catalogProductAttributeSetGroupRenameRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeSetGroupRenameRequestParam parameters
    );

    @WebResult(name = "shoppingCartTotalsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartTotalsResponseParam shoppingCartTotals(
        @WebParam(partName = "parameters", name = "shoppingCartTotalsRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartTotalsRequestParam parameters
    );

    @WebResult(name = "catalogInventoryStockItemUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogInventoryStockItemUpdateResponseParam catalogInventoryStockItemUpdate(
        @WebParam(partName = "parameters", name = "catalogInventoryStockItemUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogInventoryStockItemUpdateRequestParam parameters
    );

    @WebResult(name = "catalogCategoryAttributeListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryAttributeListResponseParam catalogCategoryAttributeList(
        @WebParam(partName = "parameters", name = "catalogCategoryAttributeListRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryAttributeListRequestParam parameters
    );

    @WebResult(name = "catalogProductDownloadableLinkRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductDownloadableLinkRemoveResponseParam catalogProductDownloadableLinkRemove(
        @WebParam(partName = "parameters", name = "catalogProductDownloadableLinkRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductDownloadableLinkRemoveRequestParam parameters
    );

    @WebResult(name = "catalogProductCustomOptionAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCustomOptionAddResponseParam catalogProductCustomOptionAdd(
        @WebParam(partName = "parameters", name = "catalogProductCustomOptionAddRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCustomOptionAddRequestParam parameters
    );

    @WebResult(name = "catalogProductListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductListResponseParam catalogProductList(
        @WebParam(partName = "parameters", name = "catalogProductListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductListRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeMediaUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaUpdateResponseParam catalogProductAttributeMediaUpdate(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaUpdateRequestParam parameters
    );

    @WebResult(name = "loginResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public LoginResponseParam login(
        @WebParam(partName = "parameters", name = "loginParam", targetNamespace = "urn:Magento")
        LoginParam parameters
    );

    @WebResult(name = "customerGroupListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerGroupListResponseParam customerGroupList(
        @WebParam(partName = "parameters", name = "customerGroupListRequestParam", targetNamespace = "urn:Magento")
        CustomerGroupListRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeSetGroupAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeSetGroupAddResponseParam catalogProductAttributeSetGroupAdd(
        @WebParam(partName = "parameters", name = "catalogProductAttributeSetGroupAddRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeSetGroupAddRequestParam parameters
    );

    @WebResult(name = "customerCustomerInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerCustomerInfoResponseParam customerCustomerInfo(
        @WebParam(partName = "parameters", name = "customerCustomerInfoRequestParam", targetNamespace = "urn:Magento")
        CustomerCustomerInfoRequestParam parameters
    );

    @WebResult(name = "shoppingCartInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartInfoResponseParam shoppingCartInfo(
        @WebParam(partName = "parameters", name = "shoppingCartInfoRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartInfoRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeMediaRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaRemoveResponseParam catalogProductAttributeMediaRemove(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaRemoveRequestParam parameters
    );

    @WebResult(name = "salesOrderCreditmemoCancelResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderCreditmemoCancelResponseParam salesOrderCreditmemoCancel(
        @WebParam(partName = "parameters", name = "salesOrderCreditmemoCancelRequestParam", targetNamespace = "urn:Magento")
        SalesOrderCreditmemoCancelRequestParam parameters
    );

    @WebResult(name = "customerAddressListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerAddressListResponseParam customerAddressList(
        @WebParam(partName = "parameters", name = "customerAddressListRequestParam", targetNamespace = "urn:Magento")
        CustomerAddressListRequestParam parameters
    );

    @WebResult(name = "shoppingCartProductAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartProductAddResponseParam shoppingCartProductAdd(
        @WebParam(partName = "parameters", name = "shoppingCartProductAddRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartProductAddRequestParam parameters
    );

    @WebResult(name = "catalogProductGetSpecialPriceResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductGetSpecialPriceResponseParam catalogProductGetSpecialPrice(
        @WebParam(partName = "parameters", name = "catalogProductGetSpecialPriceRequestParam", targetNamespace = "urn:Magento")
        CatalogProductGetSpecialPriceRequestParam parameters
    );

    @WebResult(name = "endSessionResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public EndSessionResponseParam endSession(
        @WebParam(partName = "parameters", name = "endSessionParam", targetNamespace = "urn:Magento")
        EndSessionParam parameters
    );

    @WebResult(name = "salesOrderCreditmemoCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderCreditmemoCreateResponseParam salesOrderCreditmemoCreate(
        @WebParam(partName = "parameters", name = "salesOrderCreditmemoCreateRequestParam", targetNamespace = "urn:Magento")
        SalesOrderCreditmemoCreateRequestParam parameters
    );

    @WebResult(name = "shoppingCartPaymentListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartPaymentListResponseParam shoppingCartPaymentList(
        @WebParam(partName = "parameters", name = "shoppingCartPaymentListRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartPaymentListRequestParam parameters
    );

    @WebResult(name = "catalogProductTagInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductTagInfoResponseParam catalogProductTagInfo(
        @WebParam(partName = "parameters", name = "catalogProductTagInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogProductTagInfoRequestParam parameters
    );

    @WebResult(name = "salesOrderInvoiceAddCommentResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceAddCommentResponseParam salesOrderInvoiceAddComment(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceAddCommentRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceAddCommentRequestParam parameters
    );

    @WebResult(name = "magentoInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public MagentoInfoResponseParam magentoInfo(
        @WebParam(partName = "parameters", name = "magentoInfoRequestParam", targetNamespace = "urn:Magento")
        MagentoInfoRequestParam parameters
    );

    @WebResult(name = "customerCustomerUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerCustomerUpdateResponseParam customerCustomerUpdate(
        @WebParam(partName = "parameters", name = "customerCustomerUpdateRequestParam", targetNamespace = "urn:Magento")
        CustomerCustomerUpdateRequestParam parameters
    );

    @WebResult(name = "catalogProductInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductInfoResponseParam catalogProductInfo(
        @WebParam(partName = "parameters", name = "catalogProductInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogProductInfoRequestParam parameters
    );

    @WebResult(name = "catalogProductTagUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductTagUpdateResponseParam catalogProductTagUpdate(
        @WebParam(partName = "parameters", name = "catalogProductTagUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductTagUpdateRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeRemoveResponseParam catalogProductAttributeRemove(
        @WebParam(partName = "parameters", name = "catalogProductAttributeRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeRemoveRequestParam parameters
    );

    @WebResult(name = "salesOrderShipmentListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentListResponseParam salesOrderShipmentList(
        @WebParam(partName = "parameters", name = "salesOrderShipmentListRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentListRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeSetCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeSetCreateResponseParam catalogProductAttributeSetCreate(
        @WebParam(partName = "parameters", name = "catalogProductAttributeSetCreateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeSetCreateRequestParam parameters
    );

    @WebResult(name = "catalogProductCustomOptionTypesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCustomOptionTypesResponseParam catalogProductCustomOptionTypes(
        @WebParam(partName = "parameters", name = "catalogProductCustomOptionTypesRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCustomOptionTypesRequestParam parameters
    );

    @WebResult(name = "customerCustomerCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerCustomerCreateResponseParam customerCustomerCreate(
        @WebParam(partName = "parameters", name = "customerCustomerCreateRequestParam", targetNamespace = "urn:Magento")
        CustomerCustomerCreateRequestParam parameters
    );

    @WebResult(name = "catalogProductTagListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductTagListResponseParam catalogProductTagList(
        @WebParam(partName = "parameters", name = "catalogProductTagListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductTagListRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeMediaInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaInfoResponseParam catalogProductAttributeMediaInfo(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaInfoRequestParam parameters
    );

    @WebResult(name = "salesOrderCreditmemoAddCommentResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderCreditmemoAddCommentResponseParam salesOrderCreditmemoAddComment(
        @WebParam(partName = "parameters", name = "salesOrderCreditmemoAddCommentRequestParam", targetNamespace = "urn:Magento")
        SalesOrderCreditmemoAddCommentRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeSetGroupRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeSetGroupRemoveResponseParam catalogProductAttributeSetGroupRemove(
        @WebParam(partName = "parameters", name = "catalogProductAttributeSetGroupRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeSetGroupRemoveRequestParam parameters
    );

    @WebResult(name = "catalogProductUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductUpdateResponseParam catalogProductUpdate(
        @WebParam(partName = "parameters", name = "catalogProductUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductUpdateRequestParam parameters
    );

    @WebResult(name = "callResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CallResponseParam call(
        @WebParam(partName = "parameters", name = "callParam", targetNamespace = "urn:Magento")
        CallParam parameters
    );

    @WebResult(name = "catalogProductCustomOptionInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCustomOptionInfoResponseParam catalogProductCustomOptionInfo(
        @WebParam(partName = "parameters", name = "catalogProductCustomOptionInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCustomOptionInfoRequestParam parameters
    );

    @WebResult(name = "salesOrderInvoiceCancelResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceCancelResponseParam salesOrderInvoiceCancel(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceCancelRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceCancelRequestParam parameters
    );

    @WebResult(name = "salesOrderInvoiceCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceCreateResponseParam salesOrderInvoiceCreate(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceCreateRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceCreateRequestParam parameters
    );

    @WebResult(name = "directoryRegionListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public DirectoryRegionListResponseParam directoryRegionList(
        @WebParam(partName = "parameters", name = "directoryRegionListRequestParam", targetNamespace = "urn:Magento")
        DirectoryRegionListRequestParam parameters
    );

    @WebResult(name = "catalogProductLinkAttributesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductLinkAttributesResponseParam catalogProductLinkAttributes(
        @WebParam(partName = "parameters", name = "catalogProductLinkAttributesRequestParam", targetNamespace = "urn:Magento")
        CatalogProductLinkAttributesRequestParam parameters
    );

    @WebResult(name = "shoppingCartProductMoveToCustomerQuoteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartProductMoveToCustomerQuoteResponseParam shoppingCartProductMoveToCustomerQuote(
        @WebParam(partName = "parameters", name = "shoppingCartProductMoveToCustomerQuoteRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartProductMoveToCustomerQuoteRequestParam parameters
    );

    @WebResult(name = "catalogProductCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCurrentStoreResponseParam catalogProductCurrentStore(
        @WebParam(partName = "parameters", name = "catalogProductCurrentStoreRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCurrentStoreRequestParam parameters
    );

    @WebResult(name = "customerAddressInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerAddressInfoResponseParam customerAddressInfo(
        @WebParam(partName = "parameters", name = "customerAddressInfoRequestParam", targetNamespace = "urn:Magento")
        CustomerAddressInfoRequestParam parameters
    );

    @WebResult(name = "customerCustomerDeleteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CustomerCustomerDeleteResponseParam customerCustomerDelete(
        @WebParam(partName = "parameters", name = "customerCustomerDeleteRequestParam", targetNamespace = "urn:Magento")
        CustomerCustomerDeleteRequestParam parameters
    );

    @WebResult(name = "catalogProductCustomOptionValueInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCustomOptionValueInfoResponseParam catalogProductCustomOptionValueInfo(
        @WebParam(partName = "parameters", name = "catalogProductCustomOptionValueInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCustomOptionValueInfoRequestParam parameters
    );

    @WebResult(name = "salesOrderShipmentAddTrackResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentAddTrackResponseParam salesOrderShipmentAddTrack(
        @WebParam(partName = "parameters", name = "salesOrderShipmentAddTrackRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentAddTrackRequestParam parameters
    );

    @WebResult(name = "giftMessageForQuoteItemResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftMessageForQuoteItemResponseParam giftMessageSetForQuoteItem(
        @WebParam(partName = "parameters", name = "giftMessageForQuoteItemRequestParam", targetNamespace = "urn:Magento")
        GiftMessageForQuoteItemRequestParam parameters
    );

    @WebResult(name = "catalogProductTagAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductTagAddResponseParam catalogProductTagAdd(
        @WebParam(partName = "parameters", name = "catalogProductTagAddRequestParam", targetNamespace = "urn:Magento")
        CatalogProductTagAddRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeMediaCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaCurrentStoreResponseParam catalogProductAttributeMediaCurrentStore(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaCurrentStoreRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaCurrentStoreRequestParam parameters
    );

    @WebResult(name = "catalogProductMultiUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductMultiUpdateResponseParam catalogProductMultiUpdate(
        @WebParam(partName = "parameters", name = "catalogProductMultiUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductMultiUpdateRequestParam parameters
    );

    @WebResult(name = "salesOrderShipmentAddCommentResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentAddCommentResponseParam salesOrderShipmentAddComment(
        @WebParam(partName = "parameters", name = "salesOrderShipmentAddCommentRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentAddCommentRequestParam parameters
    );

    @WebResult(name = "giftMessageForQuoteProductResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public GiftMessageForQuoteProductResponseParam giftMessageSetForQuoteProduct(
        @WebParam(partName = "parameters", name = "giftMessageForQuoteProductRequestParam", targetNamespace = "urn:Magento")
        GiftMessageForQuoteProductRequestParam parameters
    );

    @WebResult(name = "catalogCategoryLevelResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryLevelResponseParam catalogCategoryLevel(
        @WebParam(partName = "parameters", name = "catalogCategoryLevelRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryLevelRequestParam parameters
    );

    @WebResult(name = "resourcesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ResourcesResponseParam resources(
        @WebParam(partName = "parameters", name = "resourcesRequestParam", targetNamespace = "urn:Magento")
        ResourcesRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeTierPriceUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeTierPriceUpdateResponseParam catalogProductAttributeTierPriceUpdate(
        @WebParam(partName = "parameters", name = "catalogProductAttributeTierPriceUpdateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeTierPriceUpdateRequestParam parameters
    );

    @WebResult(name = "shoppingCartShippingListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartShippingListResponseParam shoppingCartShippingList(
        @WebParam(partName = "parameters", name = "shoppingCartShippingListRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartShippingListRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeCreateResponseParam catalogProductAttributeCreate(
        @WebParam(partName = "parameters", name = "catalogProductAttributeCreateRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeCreateRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeSetAttributeRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeSetAttributeRemoveResponseParam catalogProductAttributeSetAttributeRemove(
        @WebParam(partName = "parameters", name = "catalogProductAttributeSetAttributeRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeSetAttributeRemoveRequestParam parameters
    );

    @WebResult(name = "catalogProductCustomOptionRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCustomOptionRemoveResponseParam catalogProductCustomOptionRemove(
        @WebParam(partName = "parameters", name = "catalogProductCustomOptionRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCustomOptionRemoveRequestParam parameters
    );

    @WebResult(name = "shoppingCartCustomerAddressesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartCustomerAddressesResponseParam shoppingCartCustomerAddresses(
        @WebParam(partName = "parameters", name = "shoppingCartCustomerAddressesRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartCustomerAddressesRequestParam parameters
    );

    @WebResult(name = "salesOrderInvoiceCaptureResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceCaptureResponseParam salesOrderInvoiceCapture(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceCaptureRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceCaptureRequestParam parameters
    );

    @WebResult(name = "salesOrderUnholdResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderUnholdResponseParam salesOrderUnhold(
        @WebParam(partName = "parameters", name = "salesOrderUnholdRequestParam", targetNamespace = "urn:Magento")
        SalesOrderUnholdRequestParam parameters
    );

    @WebResult(name = "shoppingCartCouponRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartCouponRemoveResponseParam shoppingCartCouponRemove(
        @WebParam(partName = "parameters", name = "shoppingCartCouponRemoveRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartCouponRemoveRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeMediaListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeMediaListResponseParam catalogProductAttributeMediaList(
        @WebParam(partName = "parameters", name = "catalogProductAttributeMediaListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeMediaListRequestParam parameters
    );

    @WebResult(name = "catalogProductSetSpecialPriceResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductSetSpecialPriceResponseParam catalogProductSetSpecialPrice(
        @WebParam(partName = "parameters", name = "catalogProductSetSpecialPriceRequestParam", targetNamespace = "urn:Magento")
        CatalogProductSetSpecialPriceRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeSetAttributeAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeSetAttributeAddResponseParam catalogProductAttributeSetAttributeAdd(
        @WebParam(partName = "parameters", name = "catalogProductAttributeSetAttributeAddRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeSetAttributeAddRequestParam parameters
    );

    @WebResult(name = "shoppingCartProductListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartProductListResponseParam shoppingCartProductList(
        @WebParam(partName = "parameters", name = "shoppingCartProductListRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartProductListRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeAddOptionResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeAddOptionResponseParam catalogProductAttributeAddOption(
        @WebParam(partName = "parameters", name = "catalogProductAttributeAddOptionRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeAddOptionRequestParam parameters
    );

    @WebResult(name = "shoppingCartProductRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartProductRemoveResponseParam shoppingCartProductRemove(
        @WebParam(partName = "parameters", name = "shoppingCartProductRemoveRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartProductRemoveRequestParam parameters
    );

    @WebResult(name = "catalogProductLinkRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductLinkRemoveResponseParam catalogProductLinkRemove(
        @WebParam(partName = "parameters", name = "catalogProductLinkRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductLinkRemoveRequestParam parameters
    );

    @WebResult(name = "shoppingCartLicenseResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartLicenseResponseParam shoppingCartLicense(
        @WebParam(partName = "parameters", name = "shoppingCartLicenseRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartLicenseRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeSetListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeSetListResponseParam catalogProductAttributeSetList(
        @WebParam(partName = "parameters", name = "catalogProductAttributeSetListRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeSetListRequestParam parameters
    );

    @WebResult(name = "catalogProductCustomOptionValueRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductCustomOptionValueRemoveResponseParam catalogProductCustomOptionValueRemove(
        @WebParam(partName = "parameters", name = "catalogProductCustomOptionValueRemoveRequestParam", targetNamespace = "urn:Magento")
        CatalogProductCustomOptionValueRemoveRequestParam parameters
    );

    @WebResult(name = "salesOrderInvoiceVoidResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceVoidResponseParam salesOrderInvoiceVoid(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceVoidRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceVoidRequestParam parameters
    );

    @WebResult(name = "catalogCategoryMoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryMoveResponseParam catalogCategoryMove(
        @WebParam(partName = "parameters", name = "catalogCategoryMoveRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryMoveRequestParam parameters
    );

    @WebResult(name = "salesOrderAddCommentResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderAddCommentResponseParam salesOrderAddComment(
        @WebParam(partName = "parameters", name = "salesOrderAddCommentRequestParam", targetNamespace = "urn:Magento")
        SalesOrderAddCommentRequestParam parameters
    );

    @WebResult(name = "salesOrderHoldResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderHoldResponseParam salesOrderHold(
        @WebParam(partName = "parameters", name = "salesOrderHoldRequestParam", targetNamespace = "urn:Magento")
        SalesOrderHoldRequestParam parameters
    );

    @WebResult(name = "shoppingCartPaymentMethodResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartPaymentMethodResponseParam shoppingCartPaymentMethod(
        @WebParam(partName = "parameters", name = "shoppingCartPaymentMethodRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartPaymentMethodRequestParam parameters
    );

    @WebResult(name = "salesOrderInvoiceListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderInvoiceListResponseParam salesOrderInvoiceList(
        @WebParam(partName = "parameters", name = "salesOrderInvoiceListRequestParam", targetNamespace = "urn:Magento")
        SalesOrderInvoiceListRequestParam parameters
    );

    @WebResult(name = "catalogCategoryAssignedProductsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryAssignedProductsResponseParam catalogCategoryAssignedProducts(
        @WebParam(partName = "parameters", name = "catalogCategoryAssignedProductsRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryAssignedProductsRequestParam parameters
    );

    @WebResult(name = "shoppingCartCouponAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public ShoppingCartCouponAddResponseParam shoppingCartCouponAdd(
        @WebParam(partName = "parameters", name = "shoppingCartCouponAddRequestParam", targetNamespace = "urn:Magento")
        ShoppingCartCouponAddRequestParam parameters
    );

    @WebResult(name = "catalogProductLinkTypesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductLinkTypesResponseParam catalogProductLinkTypes(
        @WebParam(partName = "parameters", name = "catalogProductLinkTypesRequestParam", targetNamespace = "urn:Magento")
        CatalogProductLinkTypesRequestParam parameters
    );

    @WebResult(name = "salesOrderShipmentSendInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public SalesOrderShipmentSendInfoResponseParam salesOrderShipmentSendInfo(
        @WebParam(partName = "parameters", name = "salesOrderShipmentSendInfoRequestParam", targetNamespace = "urn:Magento")
        SalesOrderShipmentSendInfoRequestParam parameters
    );

    @WebResult(name = "catalogCategoryInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogCategoryInfoResponseParam catalogCategoryInfo(
        @WebParam(partName = "parameters", name = "catalogCategoryInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogCategoryInfoRequestParam parameters
    );

    @WebResult(name = "catalogProductAttributeTierPriceInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    @WebMethod
    public CatalogProductAttributeTierPriceInfoResponseParam catalogProductAttributeTierPriceInfo(
        @WebParam(partName = "parameters", name = "catalogProductAttributeTierPriceInfoRequestParam", targetNamespace = "urn:Magento")
        CatalogProductAttributeTierPriceInfoRequestParam parameters
    );
}
