
/*
 * 
 */

package com.sitewhere.assetmodule.magento.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Fri Oct 18 03:30:17 EDT 2013
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "MagentoService", 
                  wsdlLocation = "http://magento1.com/magento/index.php/api/v2_soap?wsdl",
                  targetNamespace = "urn:Magento") 
public class MagentoService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:Magento", "MagentoService");
    public final static QName MageApiModelServerWsiHandlerPort = new QName("urn:Magento", "Mage_Api_Model_Server_Wsi_HandlerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://magento1.com/magento/index.php/api/v2_soap?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://magento1.com/magento/index.php/api/v2_soap?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MagentoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MagentoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MagentoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns MageApiModelServerWsiHandlerPortType
     */
    @WebEndpoint(name = "Mage_Api_Model_Server_Wsi_HandlerPort")
    public MageApiModelServerWsiHandlerPortType getMageApiModelServerWsiHandlerPort() {
        return super.getPort(MageApiModelServerWsiHandlerPort, MageApiModelServerWsiHandlerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MageApiModelServerWsiHandlerPortType
     */
    @WebEndpoint(name = "Mage_Api_Model_Server_Wsi_HandlerPort")
    public MageApiModelServerWsiHandlerPortType getMageApiModelServerWsiHandlerPort(WebServiceFeature... features) {
        return super.getPort(MageApiModelServerWsiHandlerPort, MageApiModelServerWsiHandlerPortType.class, features);
    }

}
