
package com.sitewhere.assetmodule.magento.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.3.1
 * Fri Oct 18 03:30:17 EDT 2013
 * Generated source version: 2.3.1
 * 
 */

public final class MageApiModelServerWsiHandlerPortType_MageApiModelServerWsiHandlerPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Magento", "MagentoService");

    private MageApiModelServerWsiHandlerPortType_MageApiModelServerWsiHandlerPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MagentoService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MagentoService ss = new MagentoService(wsdlURL, SERVICE_NAME);
        MageApiModelServerWsiHandlerPortType port = ss.getMageApiModelServerWsiHandlerPort();  
        
        {
        System.out.println("Invoking catalogProductAttributeInfo...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeInfoRequestParam _catalogProductAttributeInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeInfoResponseParam _catalogProductAttributeInfo__return = port.catalogProductAttributeInfo(_catalogProductAttributeInfo_parameters);
        System.out.println("catalogProductAttributeInfo.result=" + _catalogProductAttributeInfo__return);


        }
        {
        System.out.println("Invoking catalogProductDelete...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductDeleteRequestParam _catalogProductDelete_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductDeleteResponseParam _catalogProductDelete__return = port.catalogProductDelete(_catalogProductDelete_parameters);
        System.out.println("catalogProductDelete.result=" + _catalogProductDelete__return);


        }
        {
        System.out.println("Invoking catalogProductDownloadableLinkAdd...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductDownloadableLinkAddRequestParam _catalogProductDownloadableLinkAdd_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductDownloadableLinkAddResponseParam _catalogProductDownloadableLinkAdd__return = port.catalogProductDownloadableLinkAdd(_catalogProductDownloadableLinkAdd_parameters);
        System.out.println("catalogProductDownloadableLinkAdd.result=" + _catalogProductDownloadableLinkAdd__return);


        }
        {
        System.out.println("Invoking salesOrderCreditmemoList...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderCreditmemoListRequestParam _salesOrderCreditmemoList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderCreditmemoListResponseParam _salesOrderCreditmemoList__return = port.salesOrderCreditmemoList(_salesOrderCreditmemoList_parameters);
        System.out.println("salesOrderCreditmemoList.result=" + _salesOrderCreditmemoList__return);


        }
        {
        System.out.println("Invoking catalogProductCreate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCreateRequestParam _catalogProductCreate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCreateResponseParam _catalogProductCreate__return = port.catalogProductCreate(_catalogProductCreate_parameters);
        System.out.println("catalogProductCreate.result=" + _catalogProductCreate__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeCurrentStore...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeCurrentStoreRequestParam _catalogProductAttributeCurrentStore_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeCurrentStoreResponseParam _catalogProductAttributeCurrentStore__return = port.catalogProductAttributeCurrentStore(_catalogProductAttributeCurrentStore_parameters);
        System.out.println("catalogProductAttributeCurrentStore.result=" + _catalogProductAttributeCurrentStore__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionValueList...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionValueListRequestParam _catalogProductCustomOptionValueList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionValueListResponseParam _catalogProductCustomOptionValueList__return = port.catalogProductCustomOptionValueList(_catalogProductCustomOptionValueList_parameters);
        System.out.println("catalogProductCustomOptionValueList.result=" + _catalogProductCustomOptionValueList__return);


        }
        {
        System.out.println("Invoking catalogCategoryAttributeCurrentStore...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryAttributeCurrentStoreRequestParam _catalogCategoryAttributeCurrentStore_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryAttributeCurrentStoreResponseParam _catalogCategoryAttributeCurrentStore__return = port.catalogCategoryAttributeCurrentStore(_catalogCategoryAttributeCurrentStore_parameters);
        System.out.println("catalogCategoryAttributeCurrentStore.result=" + _catalogCategoryAttributeCurrentStore__return);


        }
        {
        System.out.println("Invoking salesOrderCancel...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderCancelRequestParam _salesOrderCancel_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderCancelResponseParam _salesOrderCancel__return = port.salesOrderCancel(_salesOrderCancel_parameters);
        System.out.println("salesOrderCancel.result=" + _salesOrderCancel__return);


        }
        {
        System.out.println("Invoking resourceFaults...");
        com.sitewhere.assetmodule.magento.ws.ResourceFaultsParam _resourceFaults_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ResourceFaultsResponseParam _resourceFaults__return = port.resourceFaults(_resourceFaults_parameters);
        System.out.println("resourceFaults.result=" + _resourceFaults__return);


        }
        {
        System.out.println("Invoking giftMessageSetForQuote...");
        com.sitewhere.assetmodule.magento.ws.GiftMessageForQuoteRequestParam _giftMessageSetForQuote_parameters = null;
        com.sitewhere.assetmodule.magento.ws.GiftMessageForQuoteResponseParam _giftMessageSetForQuote__return = port.giftMessageSetForQuote(_giftMessageSetForQuote_parameters);
        System.out.println("giftMessageSetForQuote.result=" + _giftMessageSetForQuote__return);


        }
        {
        System.out.println("Invoking catalogProductTypeList...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductTypeListRequestParam _catalogProductTypeList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductTypeListResponseParam _catalogProductTypeList__return = port.catalogProductTypeList(_catalogProductTypeList_parameters);
        System.out.println("catalogProductTypeList.result=" + _catalogProductTypeList__return);


        }
        {
        System.out.println("Invoking multiCall...");
        com.sitewhere.assetmodule.magento.ws.MultiCallParam _multiCall_parameters = null;
        com.sitewhere.assetmodule.magento.ws.MultiCallResponseParam _multiCall__return = port.multiCall(_multiCall_parameters);
        System.out.println("multiCall.result=" + _multiCall__return);


        }
        {
        System.out.println("Invoking catalogProductLinkList...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductLinkListRequestParam _catalogProductLinkList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductLinkListResponseParam _catalogProductLinkList__return = port.catalogProductLinkList(_catalogProductLinkList_parameters);
        System.out.println("catalogProductLinkList.result=" + _catalogProductLinkList__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentGetCarriers...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentGetCarriersRequestParam _salesOrderShipmentGetCarriers_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentGetCarriersResponseParam _salesOrderShipmentGetCarriers__return = port.salesOrderShipmentGetCarriers(_salesOrderShipmentGetCarriers_parameters);
        System.out.println("salesOrderShipmentGetCarriers.result=" + _salesOrderShipmentGetCarriers__return);


        }
        {
        System.out.println("Invoking catalogCategoryRemoveProduct...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryRemoveProductRequestParam _catalogCategoryRemoveProduct_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryRemoveProductResponseParam _catalogCategoryRemoveProduct__return = port.catalogCategoryRemoveProduct(_catalogCategoryRemoveProduct_parameters);
        System.out.println("catalogCategoryRemoveProduct.result=" + _catalogCategoryRemoveProduct__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentCreate...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentCreateRequestParam _salesOrderShipmentCreate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentCreateResponseParam _salesOrderShipmentCreate__return = port.salesOrderShipmentCreate(_salesOrderShipmentCreate_parameters);
        System.out.println("salesOrderShipmentCreate.result=" + _salesOrderShipmentCreate__return);


        }
        {
        System.out.println("Invoking salesOrderInfo...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderInfoRequestParam _salesOrderInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderInfoResponseParam _salesOrderInfo__return = port.salesOrderInfo(_salesOrderInfo_parameters);
        System.out.println("salesOrderInfo.result=" + _salesOrderInfo__return);


        }
        {
        System.out.println("Invoking catalogProductLinkUpdate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductLinkUpdateRequestParam _catalogProductLinkUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductLinkUpdateResponseParam _catalogProductLinkUpdate__return = port.catalogProductLinkUpdate(_catalogProductLinkUpdate_parameters);
        System.out.println("catalogProductLinkUpdate.result=" + _catalogProductLinkUpdate__return);


        }
        {
        System.out.println("Invoking shoppingCartProductUpdate...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartProductUpdateRequestParam _shoppingCartProductUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartProductUpdateResponseParam _shoppingCartProductUpdate__return = port.shoppingCartProductUpdate(_shoppingCartProductUpdate_parameters);
        System.out.println("shoppingCartProductUpdate.result=" + _shoppingCartProductUpdate__return);


        }
        {
        System.out.println("Invoking catalogCategoryCurrentStore...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryCurrentStoreRequestParam _catalogCategoryCurrentStore_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryCurrentStoreResponseParam _catalogCategoryCurrentStore__return = port.catalogCategoryCurrentStore(_catalogCategoryCurrentStore_parameters);
        System.out.println("catalogCategoryCurrentStore.result=" + _catalogCategoryCurrentStore__return);


        }
        {
        System.out.println("Invoking customerAddressCreate...");
        com.sitewhere.assetmodule.magento.ws.CustomerAddressCreateRequestParam _customerAddressCreate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CustomerAddressCreateResponseParam _customerAddressCreate__return = port.customerAddressCreate(_customerAddressCreate_parameters);
        System.out.println("customerAddressCreate.result=" + _customerAddressCreate__return);


        }
        {
        System.out.println("Invoking catalogCategoryAttributeOptions...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryAttributeOptionsRequestParam _catalogCategoryAttributeOptions_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryAttributeOptionsResponseParam _catalogCategoryAttributeOptions__return = port.catalogCategoryAttributeOptions(_catalogCategoryAttributeOptions_parameters);
        System.out.println("catalogCategoryAttributeOptions.result=" + _catalogCategoryAttributeOptions__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetRemove...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetRemoveRequestParam _catalogProductAttributeSetRemove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetRemoveResponseParam _catalogProductAttributeSetRemove__return = port.catalogProductAttributeSetRemove(_catalogProductAttributeSetRemove_parameters);
        System.out.println("catalogProductAttributeSetRemove.result=" + _catalogProductAttributeSetRemove__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeOptions...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeOptionsRequestParam _catalogProductAttributeOptions_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeOptionsResponseParam _catalogProductAttributeOptions__return = port.catalogProductAttributeOptions(_catalogProductAttributeOptions_parameters);
        System.out.println("catalogProductAttributeOptions.result=" + _catalogProductAttributeOptions__return);


        }
        {
        System.out.println("Invoking salesOrderCreditmemoInfo...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderCreditmemoInfoRequestParam _salesOrderCreditmemoInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderCreditmemoInfoResponseParam _salesOrderCreditmemoInfo__return = port.salesOrderCreditmemoInfo(_salesOrderCreditmemoInfo_parameters);
        System.out.println("salesOrderCreditmemoInfo.result=" + _salesOrderCreditmemoInfo__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentInfo...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentInfoRequestParam _salesOrderShipmentInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentInfoResponseParam _salesOrderShipmentInfo__return = port.salesOrderShipmentInfo(_salesOrderShipmentInfo_parameters);
        System.out.println("salesOrderShipmentInfo.result=" + _salesOrderShipmentInfo__return);


        }
        {
        System.out.println("Invoking globalFaults...");
        com.sitewhere.assetmodule.magento.ws.GlobalFaultsParam _globalFaults_parameters = null;
        com.sitewhere.assetmodule.magento.ws.GlobalFaultsResponseParam _globalFaults__return = port.globalFaults(_globalFaults_parameters);
        System.out.println("globalFaults.result=" + _globalFaults__return);


        }
        {
        System.out.println("Invoking shoppingCartShippingMethod...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartShippingMethodRequestParam _shoppingCartShippingMethod_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartShippingMethodResponseParam _shoppingCartShippingMethod__return = port.shoppingCartShippingMethod(_shoppingCartShippingMethod_parameters);
        System.out.println("shoppingCartShippingMethod.result=" + _shoppingCartShippingMethod__return);


        }
        {
        System.out.println("Invoking catalogCategoryUpdate...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryUpdateRequestParam _catalogCategoryUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryUpdateResponseParam _catalogCategoryUpdate__return = port.catalogCategoryUpdate(_catalogCategoryUpdate_parameters);
        System.out.println("catalogCategoryUpdate.result=" + _catalogCategoryUpdate__return);


        }
        {
        System.out.println("Invoking catalogCategoryDelete...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryDeleteRequestParam _catalogCategoryDelete_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryDeleteResponseParam _catalogCategoryDelete__return = port.catalogCategoryDelete(_catalogCategoryDelete_parameters);
        System.out.println("catalogCategoryDelete.result=" + _catalogCategoryDelete__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaCreate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaCreateRequestParam _catalogProductAttributeMediaCreate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaCreateResponseParam _catalogProductAttributeMediaCreate__return = port.catalogProductAttributeMediaCreate(_catalogProductAttributeMediaCreate_parameters);
        System.out.println("catalogProductAttributeMediaCreate.result=" + _catalogProductAttributeMediaCreate__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeUpdate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeUpdateRequestParam _catalogProductAttributeUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeUpdateResponseParam _catalogProductAttributeUpdate__return = port.catalogProductAttributeUpdate(_catalogProductAttributeUpdate_parameters);
        System.out.println("catalogProductAttributeUpdate.result=" + _catalogProductAttributeUpdate__return);


        }
        {
        System.out.println("Invoking catalogInventoryStockItemList...");
        com.sitewhere.assetmodule.magento.ws.CatalogInventoryStockItemListRequestParam _catalogInventoryStockItemList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogInventoryStockItemListResponseParam _catalogInventoryStockItemList__return = port.catalogInventoryStockItemList(_catalogInventoryStockItemList_parameters);
        System.out.println("catalogInventoryStockItemList.result=" + _catalogInventoryStockItemList__return);


        }
        {
        System.out.println("Invoking shoppingCartCreate...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartCreateRequestParam _shoppingCartCreate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartCreateResponseParam _shoppingCartCreate__return = port.shoppingCartCreate(_shoppingCartCreate_parameters);
        System.out.println("shoppingCartCreate.result=" + _shoppingCartCreate__return);


        }
        {
        System.out.println("Invoking catalogProductDownloadableLinkList...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductDownloadableLinkListRequestParam _catalogProductDownloadableLinkList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductDownloadableLinkListResponseParam _catalogProductDownloadableLinkList__return = port.catalogProductDownloadableLinkList(_catalogProductDownloadableLinkList_parameters);
        System.out.println("catalogProductDownloadableLinkList.result=" + _catalogProductDownloadableLinkList__return);


        }
        {
        System.out.println("Invoking storeInfo...");
        com.sitewhere.assetmodule.magento.ws.StoreInfoRequestParam _storeInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.StoreInfoResponseParam _storeInfo__return = port.storeInfo(_storeInfo_parameters);
        System.out.println("storeInfo.result=" + _storeInfo__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaTypes...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaTypesRequestParam _catalogProductAttributeMediaTypes_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaTypesResponseParam _catalogProductAttributeMediaTypes__return = port.catalogProductAttributeMediaTypes(_catalogProductAttributeMediaTypes_parameters);
        System.out.println("catalogProductAttributeMediaTypes.result=" + _catalogProductAttributeMediaTypes__return);


        }
        {
        System.out.println("Invoking customerCustomerList...");
        com.sitewhere.assetmodule.magento.ws.CustomerCustomerListRequestParam _customerCustomerList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CustomerCustomerListResponseParam _customerCustomerList__return = port.customerCustomerList(_customerCustomerList_parameters);
        System.out.println("customerCustomerList.result=" + _customerCustomerList__return);


        }
        {
        System.out.println("Invoking directoryCountryList...");
        com.sitewhere.assetmodule.magento.ws.DirectoryCountryListRequestParam _directoryCountryList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.DirectoryCountryListResponseParam _directoryCountryList__return = port.directoryCountryList(_directoryCountryList_parameters);
        System.out.println("directoryCountryList.result=" + _directoryCountryList__return);


        }
        {
        System.out.println("Invoking storeList...");
        com.sitewhere.assetmodule.magento.ws.StoreListRequestParam _storeList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.StoreListResponseParam _storeList__return = port.storeList(_storeList_parameters);
        System.out.println("storeList.result=" + _storeList__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceInfo...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceInfoRequestParam _salesOrderInvoiceInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceInfoResponseParam _salesOrderInvoiceInfo__return = port.salesOrderInvoiceInfo(_salesOrderInvoiceInfo_parameters);
        System.out.println("salesOrderInvoiceInfo.result=" + _salesOrderInvoiceInfo__return);


        }
        {
        System.out.println("Invoking catalogInventoryStockItemMultiUpdate...");
        com.sitewhere.assetmodule.magento.ws.CatalogInventoryStockItemMultiUpdateRequestParam _catalogInventoryStockItemMultiUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogInventoryStockItemMultiUpdateResponseParam _catalogInventoryStockItemMultiUpdate__return = port.catalogInventoryStockItemMultiUpdate(_catalogInventoryStockItemMultiUpdate_parameters);
        System.out.println("catalogInventoryStockItemMultiUpdate.result=" + _catalogInventoryStockItemMultiUpdate__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionValueUpdate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionValueUpdateRequestParam _catalogProductCustomOptionValueUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionValueUpdateResponseParam _catalogProductCustomOptionValueUpdate__return = port.catalogProductCustomOptionValueUpdate(_catalogProductCustomOptionValueUpdate_parameters);
        System.out.println("catalogProductCustomOptionValueUpdate.result=" + _catalogProductCustomOptionValueUpdate__return);


        }
        {
        System.out.println("Invoking catalogProductTagRemove...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductTagRemoveRequestParam _catalogProductTagRemove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductTagRemoveResponseParam _catalogProductTagRemove__return = port.catalogProductTagRemove(_catalogProductTagRemove_parameters);
        System.out.println("catalogProductTagRemove.result=" + _catalogProductTagRemove__return);


        }
        {
        System.out.println("Invoking customerAddressDelete...");
        com.sitewhere.assetmodule.magento.ws.CustomerAddressDeleteRequestParam _customerAddressDelete_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CustomerAddressDeleteResponseParam _customerAddressDelete__return = port.customerAddressDelete(_customerAddressDelete_parameters);
        System.out.println("customerAddressDelete.result=" + _customerAddressDelete__return);


        }
        {
        System.out.println("Invoking startSession...");
        com.sitewhere.assetmodule.magento.ws.StartSessionResponseParam _startSession__return = port.startSession();
        System.out.println("startSession.result=" + _startSession__return);


        }
        {
        System.out.println("Invoking salesOrderList...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderListRequestParam _salesOrderList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderListResponseParam _salesOrderList__return = port.salesOrderList(_salesOrderList_parameters);
        System.out.println("salesOrderList.result=" + _salesOrderList__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionValueAdd...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionValueAddRequestParam _catalogProductCustomOptionValueAdd_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionValueAddResponseParam _catalogProductCustomOptionValueAdd__return = port.catalogProductCustomOptionValueAdd(_catalogProductCustomOptionValueAdd_parameters);
        System.out.println("catalogProductCustomOptionValueAdd.result=" + _catalogProductCustomOptionValueAdd__return);


        }
        {
        System.out.println("Invoking catalogCategoryUpdateProduct...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryUpdateProductRequestParam _catalogCategoryUpdateProduct_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryUpdateProductResponseParam _catalogCategoryUpdateProduct__return = port.catalogCategoryUpdateProduct(_catalogCategoryUpdateProduct_parameters);
        System.out.println("catalogCategoryUpdateProduct.result=" + _catalogCategoryUpdateProduct__return);


        }
        {
        System.out.println("Invoking shoppingCartCustomerSet...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartCustomerSetRequestParam _shoppingCartCustomerSet_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartCustomerSetResponseParam _shoppingCartCustomerSet__return = port.shoppingCartCustomerSet(_shoppingCartCustomerSet_parameters);
        System.out.println("shoppingCartCustomerSet.result=" + _shoppingCartCustomerSet__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentRemoveTrack...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentRemoveTrackRequestParam _salesOrderShipmentRemoveTrack_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentRemoveTrackResponseParam _salesOrderShipmentRemoveTrack__return = port.salesOrderShipmentRemoveTrack(_salesOrderShipmentRemoveTrack_parameters);
        System.out.println("salesOrderShipmentRemoveTrack.result=" + _salesOrderShipmentRemoveTrack__return);


        }
        {
        System.out.println("Invoking catalogCategoryTree...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryTreeRequestParam _catalogCategoryTree_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryTreeResponseParam _catalogCategoryTree__return = port.catalogCategoryTree(_catalogCategoryTree_parameters);
        System.out.println("catalogCategoryTree.result=" + _catalogCategoryTree__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeList...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeListRequestParam _catalogProductAttributeList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeListResponseParam _catalogProductAttributeList__return = port.catalogProductAttributeList(_catalogProductAttributeList_parameters);
        System.out.println("catalogProductAttributeList.result=" + _catalogProductAttributeList__return);


        }
        {
        System.out.println("Invoking catalogProductLinkAssign...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductLinkAssignRequestParam _catalogProductLinkAssign_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductLinkAssignResponseParam _catalogProductLinkAssign__return = port.catalogProductLinkAssign(_catalogProductLinkAssign_parameters);
        System.out.println("catalogProductLinkAssign.result=" + _catalogProductLinkAssign__return);


        }
        {
        System.out.println("Invoking catalogCategoryAssignProduct...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryAssignProductRequestParam _catalogCategoryAssignProduct_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryAssignProductResponseParam _catalogCategoryAssignProduct__return = port.catalogCategoryAssignProduct(_catalogCategoryAssignProduct_parameters);
        System.out.println("catalogCategoryAssignProduct.result=" + _catalogCategoryAssignProduct__return);


        }
        {
        System.out.println("Invoking catalogCategoryCreate...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryCreateRequestParam _catalogCategoryCreate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryCreateResponseParam _catalogCategoryCreate__return = port.catalogCategoryCreate(_catalogCategoryCreate_parameters);
        System.out.println("catalogCategoryCreate.result=" + _catalogCategoryCreate__return);


        }
        {
        System.out.println("Invoking shoppingCartOrder...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartOrderRequestParam _shoppingCartOrder_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartOrderResponseParam _shoppingCartOrder__return = port.shoppingCartOrder(_shoppingCartOrder_parameters);
        System.out.println("shoppingCartOrder.result=" + _shoppingCartOrder__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionUpdate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionUpdateRequestParam _catalogProductCustomOptionUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionUpdateResponseParam _catalogProductCustomOptionUpdate__return = port.catalogProductCustomOptionUpdate(_catalogProductCustomOptionUpdate_parameters);
        System.out.println("catalogProductCustomOptionUpdate.result=" + _catalogProductCustomOptionUpdate__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionList...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionListRequestParam _catalogProductCustomOptionList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionListResponseParam _catalogProductCustomOptionList__return = port.catalogProductCustomOptionList(_catalogProductCustomOptionList_parameters);
        System.out.println("catalogProductCustomOptionList.result=" + _catalogProductCustomOptionList__return);


        }
        {
        System.out.println("Invoking customerAddressUpdate...");
        com.sitewhere.assetmodule.magento.ws.CustomerAddressUpdateRequestParam _customerAddressUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CustomerAddressUpdateResponseParam _customerAddressUpdate__return = port.customerAddressUpdate(_customerAddressUpdate_parameters);
        System.out.println("customerAddressUpdate.result=" + _customerAddressUpdate__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetGroupRename...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetGroupRenameRequestParam _catalogProductAttributeSetGroupRename_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetGroupRenameResponseParam _catalogProductAttributeSetGroupRename__return = port.catalogProductAttributeSetGroupRename(_catalogProductAttributeSetGroupRename_parameters);
        System.out.println("catalogProductAttributeSetGroupRename.result=" + _catalogProductAttributeSetGroupRename__return);


        }
        {
        System.out.println("Invoking shoppingCartTotals...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartTotalsRequestParam _shoppingCartTotals_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartTotalsResponseParam _shoppingCartTotals__return = port.shoppingCartTotals(_shoppingCartTotals_parameters);
        System.out.println("shoppingCartTotals.result=" + _shoppingCartTotals__return);


        }
        {
        System.out.println("Invoking catalogInventoryStockItemUpdate...");
        com.sitewhere.assetmodule.magento.ws.CatalogInventoryStockItemUpdateRequestParam _catalogInventoryStockItemUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogInventoryStockItemUpdateResponseParam _catalogInventoryStockItemUpdate__return = port.catalogInventoryStockItemUpdate(_catalogInventoryStockItemUpdate_parameters);
        System.out.println("catalogInventoryStockItemUpdate.result=" + _catalogInventoryStockItemUpdate__return);


        }
        {
        System.out.println("Invoking catalogCategoryAttributeList...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryAttributeListRequestParam _catalogCategoryAttributeList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryAttributeListResponseParam _catalogCategoryAttributeList__return = port.catalogCategoryAttributeList(_catalogCategoryAttributeList_parameters);
        System.out.println("catalogCategoryAttributeList.result=" + _catalogCategoryAttributeList__return);


        }
        {
        System.out.println("Invoking catalogProductDownloadableLinkRemove...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductDownloadableLinkRemoveRequestParam _catalogProductDownloadableLinkRemove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductDownloadableLinkRemoveResponseParam _catalogProductDownloadableLinkRemove__return = port.catalogProductDownloadableLinkRemove(_catalogProductDownloadableLinkRemove_parameters);
        System.out.println("catalogProductDownloadableLinkRemove.result=" + _catalogProductDownloadableLinkRemove__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionAdd...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionAddRequestParam _catalogProductCustomOptionAdd_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionAddResponseParam _catalogProductCustomOptionAdd__return = port.catalogProductCustomOptionAdd(_catalogProductCustomOptionAdd_parameters);
        System.out.println("catalogProductCustomOptionAdd.result=" + _catalogProductCustomOptionAdd__return);


        }
        {
        System.out.println("Invoking catalogProductList...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductListRequestParam _catalogProductList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductListResponseParam _catalogProductList__return = port.catalogProductList(_catalogProductList_parameters);
        System.out.println("catalogProductList.result=" + _catalogProductList__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaUpdate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaUpdateRequestParam _catalogProductAttributeMediaUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaUpdateResponseParam _catalogProductAttributeMediaUpdate__return = port.catalogProductAttributeMediaUpdate(_catalogProductAttributeMediaUpdate_parameters);
        System.out.println("catalogProductAttributeMediaUpdate.result=" + _catalogProductAttributeMediaUpdate__return);


        }
        {
        System.out.println("Invoking login...");
        com.sitewhere.assetmodule.magento.ws.LoginParam _login_parameters = null;
        com.sitewhere.assetmodule.magento.ws.LoginResponseParam _login__return = port.login(_login_parameters);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking customerGroupList...");
        com.sitewhere.assetmodule.magento.ws.CustomerGroupListRequestParam _customerGroupList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CustomerGroupListResponseParam _customerGroupList__return = port.customerGroupList(_customerGroupList_parameters);
        System.out.println("customerGroupList.result=" + _customerGroupList__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetGroupAdd...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetGroupAddRequestParam _catalogProductAttributeSetGroupAdd_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetGroupAddResponseParam _catalogProductAttributeSetGroupAdd__return = port.catalogProductAttributeSetGroupAdd(_catalogProductAttributeSetGroupAdd_parameters);
        System.out.println("catalogProductAttributeSetGroupAdd.result=" + _catalogProductAttributeSetGroupAdd__return);


        }
        {
        System.out.println("Invoking customerCustomerInfo...");
        com.sitewhere.assetmodule.magento.ws.CustomerCustomerInfoRequestParam _customerCustomerInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CustomerCustomerInfoResponseParam _customerCustomerInfo__return = port.customerCustomerInfo(_customerCustomerInfo_parameters);
        System.out.println("customerCustomerInfo.result=" + _customerCustomerInfo__return);


        }
        {
        System.out.println("Invoking shoppingCartInfo...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartInfoRequestParam _shoppingCartInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartInfoResponseParam _shoppingCartInfo__return = port.shoppingCartInfo(_shoppingCartInfo_parameters);
        System.out.println("shoppingCartInfo.result=" + _shoppingCartInfo__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaRemove...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaRemoveRequestParam _catalogProductAttributeMediaRemove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaRemoveResponseParam _catalogProductAttributeMediaRemove__return = port.catalogProductAttributeMediaRemove(_catalogProductAttributeMediaRemove_parameters);
        System.out.println("catalogProductAttributeMediaRemove.result=" + _catalogProductAttributeMediaRemove__return);


        }
        {
        System.out.println("Invoking salesOrderCreditmemoCancel...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderCreditmemoCancelRequestParam _salesOrderCreditmemoCancel_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderCreditmemoCancelResponseParam _salesOrderCreditmemoCancel__return = port.salesOrderCreditmemoCancel(_salesOrderCreditmemoCancel_parameters);
        System.out.println("salesOrderCreditmemoCancel.result=" + _salesOrderCreditmemoCancel__return);


        }
        {
        System.out.println("Invoking customerAddressList...");
        com.sitewhere.assetmodule.magento.ws.CustomerAddressListRequestParam _customerAddressList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CustomerAddressListResponseParam _customerAddressList__return = port.customerAddressList(_customerAddressList_parameters);
        System.out.println("customerAddressList.result=" + _customerAddressList__return);


        }
        {
        System.out.println("Invoking shoppingCartProductAdd...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartProductAddRequestParam _shoppingCartProductAdd_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartProductAddResponseParam _shoppingCartProductAdd__return = port.shoppingCartProductAdd(_shoppingCartProductAdd_parameters);
        System.out.println("shoppingCartProductAdd.result=" + _shoppingCartProductAdd__return);


        }
        {
        System.out.println("Invoking catalogProductGetSpecialPrice...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductGetSpecialPriceRequestParam _catalogProductGetSpecialPrice_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductGetSpecialPriceResponseParam _catalogProductGetSpecialPrice__return = port.catalogProductGetSpecialPrice(_catalogProductGetSpecialPrice_parameters);
        System.out.println("catalogProductGetSpecialPrice.result=" + _catalogProductGetSpecialPrice__return);


        }
        {
        System.out.println("Invoking endSession...");
        com.sitewhere.assetmodule.magento.ws.EndSessionParam _endSession_parameters = null;
        com.sitewhere.assetmodule.magento.ws.EndSessionResponseParam _endSession__return = port.endSession(_endSession_parameters);
        System.out.println("endSession.result=" + _endSession__return);


        }
        {
        System.out.println("Invoking salesOrderCreditmemoCreate...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderCreditmemoCreateRequestParam _salesOrderCreditmemoCreate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderCreditmemoCreateResponseParam _salesOrderCreditmemoCreate__return = port.salesOrderCreditmemoCreate(_salesOrderCreditmemoCreate_parameters);
        System.out.println("salesOrderCreditmemoCreate.result=" + _salesOrderCreditmemoCreate__return);


        }
        {
        System.out.println("Invoking shoppingCartPaymentList...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartPaymentListRequestParam _shoppingCartPaymentList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartPaymentListResponseParam _shoppingCartPaymentList__return = port.shoppingCartPaymentList(_shoppingCartPaymentList_parameters);
        System.out.println("shoppingCartPaymentList.result=" + _shoppingCartPaymentList__return);


        }
        {
        System.out.println("Invoking catalogProductTagInfo...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductTagInfoRequestParam _catalogProductTagInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductTagInfoResponseParam _catalogProductTagInfo__return = port.catalogProductTagInfo(_catalogProductTagInfo_parameters);
        System.out.println("catalogProductTagInfo.result=" + _catalogProductTagInfo__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceAddComment...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceAddCommentRequestParam _salesOrderInvoiceAddComment_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceAddCommentResponseParam _salesOrderInvoiceAddComment__return = port.salesOrderInvoiceAddComment(_salesOrderInvoiceAddComment_parameters);
        System.out.println("salesOrderInvoiceAddComment.result=" + _salesOrderInvoiceAddComment__return);


        }
        {
        System.out.println("Invoking magentoInfo...");
        com.sitewhere.assetmodule.magento.ws.MagentoInfoRequestParam _magentoInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.MagentoInfoResponseParam _magentoInfo__return = port.magentoInfo(_magentoInfo_parameters);
        System.out.println("magentoInfo.result=" + _magentoInfo__return);


        }
        {
        System.out.println("Invoking customerCustomerUpdate...");
        com.sitewhere.assetmodule.magento.ws.CustomerCustomerUpdateRequestParam _customerCustomerUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CustomerCustomerUpdateResponseParam _customerCustomerUpdate__return = port.customerCustomerUpdate(_customerCustomerUpdate_parameters);
        System.out.println("customerCustomerUpdate.result=" + _customerCustomerUpdate__return);


        }
        {
        System.out.println("Invoking catalogProductInfo...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductInfoRequestParam _catalogProductInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductInfoResponseParam _catalogProductInfo__return = port.catalogProductInfo(_catalogProductInfo_parameters);
        System.out.println("catalogProductInfo.result=" + _catalogProductInfo__return);


        }
        {
        System.out.println("Invoking catalogProductTagUpdate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductTagUpdateRequestParam _catalogProductTagUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductTagUpdateResponseParam _catalogProductTagUpdate__return = port.catalogProductTagUpdate(_catalogProductTagUpdate_parameters);
        System.out.println("catalogProductTagUpdate.result=" + _catalogProductTagUpdate__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeRemove...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeRemoveRequestParam _catalogProductAttributeRemove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeRemoveResponseParam _catalogProductAttributeRemove__return = port.catalogProductAttributeRemove(_catalogProductAttributeRemove_parameters);
        System.out.println("catalogProductAttributeRemove.result=" + _catalogProductAttributeRemove__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentList...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentListRequestParam _salesOrderShipmentList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentListResponseParam _salesOrderShipmentList__return = port.salesOrderShipmentList(_salesOrderShipmentList_parameters);
        System.out.println("salesOrderShipmentList.result=" + _salesOrderShipmentList__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetCreate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetCreateRequestParam _catalogProductAttributeSetCreate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetCreateResponseParam _catalogProductAttributeSetCreate__return = port.catalogProductAttributeSetCreate(_catalogProductAttributeSetCreate_parameters);
        System.out.println("catalogProductAttributeSetCreate.result=" + _catalogProductAttributeSetCreate__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionTypes...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionTypesRequestParam _catalogProductCustomOptionTypes_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionTypesResponseParam _catalogProductCustomOptionTypes__return = port.catalogProductCustomOptionTypes(_catalogProductCustomOptionTypes_parameters);
        System.out.println("catalogProductCustomOptionTypes.result=" + _catalogProductCustomOptionTypes__return);


        }
        {
        System.out.println("Invoking customerCustomerCreate...");
        com.sitewhere.assetmodule.magento.ws.CustomerCustomerCreateRequestParam _customerCustomerCreate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CustomerCustomerCreateResponseParam _customerCustomerCreate__return = port.customerCustomerCreate(_customerCustomerCreate_parameters);
        System.out.println("customerCustomerCreate.result=" + _customerCustomerCreate__return);


        }
        {
        System.out.println("Invoking catalogProductTagList...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductTagListRequestParam _catalogProductTagList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductTagListResponseParam _catalogProductTagList__return = port.catalogProductTagList(_catalogProductTagList_parameters);
        System.out.println("catalogProductTagList.result=" + _catalogProductTagList__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaInfo...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaInfoRequestParam _catalogProductAttributeMediaInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaInfoResponseParam _catalogProductAttributeMediaInfo__return = port.catalogProductAttributeMediaInfo(_catalogProductAttributeMediaInfo_parameters);
        System.out.println("catalogProductAttributeMediaInfo.result=" + _catalogProductAttributeMediaInfo__return);


        }
        {
        System.out.println("Invoking salesOrderCreditmemoAddComment...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderCreditmemoAddCommentRequestParam _salesOrderCreditmemoAddComment_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderCreditmemoAddCommentResponseParam _salesOrderCreditmemoAddComment__return = port.salesOrderCreditmemoAddComment(_salesOrderCreditmemoAddComment_parameters);
        System.out.println("salesOrderCreditmemoAddComment.result=" + _salesOrderCreditmemoAddComment__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetGroupRemove...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetGroupRemoveRequestParam _catalogProductAttributeSetGroupRemove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetGroupRemoveResponseParam _catalogProductAttributeSetGroupRemove__return = port.catalogProductAttributeSetGroupRemove(_catalogProductAttributeSetGroupRemove_parameters);
        System.out.println("catalogProductAttributeSetGroupRemove.result=" + _catalogProductAttributeSetGroupRemove__return);


        }
        {
        System.out.println("Invoking catalogProductUpdate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductUpdateRequestParam _catalogProductUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductUpdateResponseParam _catalogProductUpdate__return = port.catalogProductUpdate(_catalogProductUpdate_parameters);
        System.out.println("catalogProductUpdate.result=" + _catalogProductUpdate__return);


        }
        {
        System.out.println("Invoking call...");
        com.sitewhere.assetmodule.magento.ws.CallParam _call_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CallResponseParam _call__return = port.call(_call_parameters);
        System.out.println("call.result=" + _call__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionInfo...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionInfoRequestParam _catalogProductCustomOptionInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionInfoResponseParam _catalogProductCustomOptionInfo__return = port.catalogProductCustomOptionInfo(_catalogProductCustomOptionInfo_parameters);
        System.out.println("catalogProductCustomOptionInfo.result=" + _catalogProductCustomOptionInfo__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceCancel...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceCancelRequestParam _salesOrderInvoiceCancel_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceCancelResponseParam _salesOrderInvoiceCancel__return = port.salesOrderInvoiceCancel(_salesOrderInvoiceCancel_parameters);
        System.out.println("salesOrderInvoiceCancel.result=" + _salesOrderInvoiceCancel__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceCreate...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceCreateRequestParam _salesOrderInvoiceCreate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceCreateResponseParam _salesOrderInvoiceCreate__return = port.salesOrderInvoiceCreate(_salesOrderInvoiceCreate_parameters);
        System.out.println("salesOrderInvoiceCreate.result=" + _salesOrderInvoiceCreate__return);


        }
        {
        System.out.println("Invoking directoryRegionList...");
        com.sitewhere.assetmodule.magento.ws.DirectoryRegionListRequestParam _directoryRegionList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.DirectoryRegionListResponseParam _directoryRegionList__return = port.directoryRegionList(_directoryRegionList_parameters);
        System.out.println("directoryRegionList.result=" + _directoryRegionList__return);


        }
        {
        System.out.println("Invoking catalogProductLinkAttributes...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductLinkAttributesRequestParam _catalogProductLinkAttributes_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductLinkAttributesResponseParam _catalogProductLinkAttributes__return = port.catalogProductLinkAttributes(_catalogProductLinkAttributes_parameters);
        System.out.println("catalogProductLinkAttributes.result=" + _catalogProductLinkAttributes__return);


        }
        {
        System.out.println("Invoking shoppingCartProductMoveToCustomerQuote...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartProductMoveToCustomerQuoteRequestParam _shoppingCartProductMoveToCustomerQuote_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartProductMoveToCustomerQuoteResponseParam _shoppingCartProductMoveToCustomerQuote__return = port.shoppingCartProductMoveToCustomerQuote(_shoppingCartProductMoveToCustomerQuote_parameters);
        System.out.println("shoppingCartProductMoveToCustomerQuote.result=" + _shoppingCartProductMoveToCustomerQuote__return);


        }
        {
        System.out.println("Invoking catalogProductCurrentStore...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCurrentStoreRequestParam _catalogProductCurrentStore_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCurrentStoreResponseParam _catalogProductCurrentStore__return = port.catalogProductCurrentStore(_catalogProductCurrentStore_parameters);
        System.out.println("catalogProductCurrentStore.result=" + _catalogProductCurrentStore__return);


        }
        {
        System.out.println("Invoking customerAddressInfo...");
        com.sitewhere.assetmodule.magento.ws.CustomerAddressInfoRequestParam _customerAddressInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CustomerAddressInfoResponseParam _customerAddressInfo__return = port.customerAddressInfo(_customerAddressInfo_parameters);
        System.out.println("customerAddressInfo.result=" + _customerAddressInfo__return);


        }
        {
        System.out.println("Invoking customerCustomerDelete...");
        com.sitewhere.assetmodule.magento.ws.CustomerCustomerDeleteRequestParam _customerCustomerDelete_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CustomerCustomerDeleteResponseParam _customerCustomerDelete__return = port.customerCustomerDelete(_customerCustomerDelete_parameters);
        System.out.println("customerCustomerDelete.result=" + _customerCustomerDelete__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionValueInfo...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionValueInfoRequestParam _catalogProductCustomOptionValueInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionValueInfoResponseParam _catalogProductCustomOptionValueInfo__return = port.catalogProductCustomOptionValueInfo(_catalogProductCustomOptionValueInfo_parameters);
        System.out.println("catalogProductCustomOptionValueInfo.result=" + _catalogProductCustomOptionValueInfo__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentAddTrack...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentAddTrackRequestParam _salesOrderShipmentAddTrack_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentAddTrackResponseParam _salesOrderShipmentAddTrack__return = port.salesOrderShipmentAddTrack(_salesOrderShipmentAddTrack_parameters);
        System.out.println("salesOrderShipmentAddTrack.result=" + _salesOrderShipmentAddTrack__return);


        }
        {
        System.out.println("Invoking giftMessageSetForQuoteItem...");
        com.sitewhere.assetmodule.magento.ws.GiftMessageForQuoteItemRequestParam _giftMessageSetForQuoteItem_parameters = null;
        com.sitewhere.assetmodule.magento.ws.GiftMessageForQuoteItemResponseParam _giftMessageSetForQuoteItem__return = port.giftMessageSetForQuoteItem(_giftMessageSetForQuoteItem_parameters);
        System.out.println("giftMessageSetForQuoteItem.result=" + _giftMessageSetForQuoteItem__return);


        }
        {
        System.out.println("Invoking catalogProductTagAdd...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductTagAddRequestParam _catalogProductTagAdd_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductTagAddResponseParam _catalogProductTagAdd__return = port.catalogProductTagAdd(_catalogProductTagAdd_parameters);
        System.out.println("catalogProductTagAdd.result=" + _catalogProductTagAdd__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaCurrentStore...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaCurrentStoreRequestParam _catalogProductAttributeMediaCurrentStore_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaCurrentStoreResponseParam _catalogProductAttributeMediaCurrentStore__return = port.catalogProductAttributeMediaCurrentStore(_catalogProductAttributeMediaCurrentStore_parameters);
        System.out.println("catalogProductAttributeMediaCurrentStore.result=" + _catalogProductAttributeMediaCurrentStore__return);


        }
        {
        System.out.println("Invoking catalogProductMultiUpdate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductMultiUpdateRequestParam _catalogProductMultiUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductMultiUpdateResponseParam _catalogProductMultiUpdate__return = port.catalogProductMultiUpdate(_catalogProductMultiUpdate_parameters);
        System.out.println("catalogProductMultiUpdate.result=" + _catalogProductMultiUpdate__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentAddComment...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentAddCommentRequestParam _salesOrderShipmentAddComment_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentAddCommentResponseParam _salesOrderShipmentAddComment__return = port.salesOrderShipmentAddComment(_salesOrderShipmentAddComment_parameters);
        System.out.println("salesOrderShipmentAddComment.result=" + _salesOrderShipmentAddComment__return);


        }
        {
        System.out.println("Invoking giftMessageSetForQuoteProduct...");
        com.sitewhere.assetmodule.magento.ws.GiftMessageForQuoteProductRequestParam _giftMessageSetForQuoteProduct_parameters = null;
        com.sitewhere.assetmodule.magento.ws.GiftMessageForQuoteProductResponseParam _giftMessageSetForQuoteProduct__return = port.giftMessageSetForQuoteProduct(_giftMessageSetForQuoteProduct_parameters);
        System.out.println("giftMessageSetForQuoteProduct.result=" + _giftMessageSetForQuoteProduct__return);


        }
        {
        System.out.println("Invoking catalogCategoryLevel...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryLevelRequestParam _catalogCategoryLevel_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryLevelResponseParam _catalogCategoryLevel__return = port.catalogCategoryLevel(_catalogCategoryLevel_parameters);
        System.out.println("catalogCategoryLevel.result=" + _catalogCategoryLevel__return);


        }
        {
        System.out.println("Invoking resources...");
        com.sitewhere.assetmodule.magento.ws.ResourcesRequestParam _resources_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ResourcesResponseParam _resources__return = port.resources(_resources_parameters);
        System.out.println("resources.result=" + _resources__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeTierPriceUpdate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeTierPriceUpdateRequestParam _catalogProductAttributeTierPriceUpdate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeTierPriceUpdateResponseParam _catalogProductAttributeTierPriceUpdate__return = port.catalogProductAttributeTierPriceUpdate(_catalogProductAttributeTierPriceUpdate_parameters);
        System.out.println("catalogProductAttributeTierPriceUpdate.result=" + _catalogProductAttributeTierPriceUpdate__return);


        }
        {
        System.out.println("Invoking shoppingCartShippingList...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartShippingListRequestParam _shoppingCartShippingList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartShippingListResponseParam _shoppingCartShippingList__return = port.shoppingCartShippingList(_shoppingCartShippingList_parameters);
        System.out.println("shoppingCartShippingList.result=" + _shoppingCartShippingList__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeCreate...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeCreateRequestParam _catalogProductAttributeCreate_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeCreateResponseParam _catalogProductAttributeCreate__return = port.catalogProductAttributeCreate(_catalogProductAttributeCreate_parameters);
        System.out.println("catalogProductAttributeCreate.result=" + _catalogProductAttributeCreate__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetAttributeRemove...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetAttributeRemoveRequestParam _catalogProductAttributeSetAttributeRemove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetAttributeRemoveResponseParam _catalogProductAttributeSetAttributeRemove__return = port.catalogProductAttributeSetAttributeRemove(_catalogProductAttributeSetAttributeRemove_parameters);
        System.out.println("catalogProductAttributeSetAttributeRemove.result=" + _catalogProductAttributeSetAttributeRemove__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionRemove...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionRemoveRequestParam _catalogProductCustomOptionRemove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionRemoveResponseParam _catalogProductCustomOptionRemove__return = port.catalogProductCustomOptionRemove(_catalogProductCustomOptionRemove_parameters);
        System.out.println("catalogProductCustomOptionRemove.result=" + _catalogProductCustomOptionRemove__return);


        }
        {
        System.out.println("Invoking shoppingCartCustomerAddresses...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartCustomerAddressesRequestParam _shoppingCartCustomerAddresses_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartCustomerAddressesResponseParam _shoppingCartCustomerAddresses__return = port.shoppingCartCustomerAddresses(_shoppingCartCustomerAddresses_parameters);
        System.out.println("shoppingCartCustomerAddresses.result=" + _shoppingCartCustomerAddresses__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceCapture...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceCaptureRequestParam _salesOrderInvoiceCapture_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceCaptureResponseParam _salesOrderInvoiceCapture__return = port.salesOrderInvoiceCapture(_salesOrderInvoiceCapture_parameters);
        System.out.println("salesOrderInvoiceCapture.result=" + _salesOrderInvoiceCapture__return);


        }
        {
        System.out.println("Invoking salesOrderUnhold...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderUnholdRequestParam _salesOrderUnhold_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderUnholdResponseParam _salesOrderUnhold__return = port.salesOrderUnhold(_salesOrderUnhold_parameters);
        System.out.println("salesOrderUnhold.result=" + _salesOrderUnhold__return);


        }
        {
        System.out.println("Invoking shoppingCartCouponRemove...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartCouponRemoveRequestParam _shoppingCartCouponRemove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartCouponRemoveResponseParam _shoppingCartCouponRemove__return = port.shoppingCartCouponRemove(_shoppingCartCouponRemove_parameters);
        System.out.println("shoppingCartCouponRemove.result=" + _shoppingCartCouponRemove__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaList...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaListRequestParam _catalogProductAttributeMediaList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeMediaListResponseParam _catalogProductAttributeMediaList__return = port.catalogProductAttributeMediaList(_catalogProductAttributeMediaList_parameters);
        System.out.println("catalogProductAttributeMediaList.result=" + _catalogProductAttributeMediaList__return);


        }
        {
        System.out.println("Invoking catalogProductSetSpecialPrice...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductSetSpecialPriceRequestParam _catalogProductSetSpecialPrice_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductSetSpecialPriceResponseParam _catalogProductSetSpecialPrice__return = port.catalogProductSetSpecialPrice(_catalogProductSetSpecialPrice_parameters);
        System.out.println("catalogProductSetSpecialPrice.result=" + _catalogProductSetSpecialPrice__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetAttributeAdd...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetAttributeAddRequestParam _catalogProductAttributeSetAttributeAdd_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetAttributeAddResponseParam _catalogProductAttributeSetAttributeAdd__return = port.catalogProductAttributeSetAttributeAdd(_catalogProductAttributeSetAttributeAdd_parameters);
        System.out.println("catalogProductAttributeSetAttributeAdd.result=" + _catalogProductAttributeSetAttributeAdd__return);


        }
        {
        System.out.println("Invoking shoppingCartProductList...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartProductListRequestParam _shoppingCartProductList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartProductListResponseParam _shoppingCartProductList__return = port.shoppingCartProductList(_shoppingCartProductList_parameters);
        System.out.println("shoppingCartProductList.result=" + _shoppingCartProductList__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeAddOption...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeAddOptionRequestParam _catalogProductAttributeAddOption_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeAddOptionResponseParam _catalogProductAttributeAddOption__return = port.catalogProductAttributeAddOption(_catalogProductAttributeAddOption_parameters);
        System.out.println("catalogProductAttributeAddOption.result=" + _catalogProductAttributeAddOption__return);


        }
        {
        System.out.println("Invoking shoppingCartProductRemove...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartProductRemoveRequestParam _shoppingCartProductRemove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartProductRemoveResponseParam _shoppingCartProductRemove__return = port.shoppingCartProductRemove(_shoppingCartProductRemove_parameters);
        System.out.println("shoppingCartProductRemove.result=" + _shoppingCartProductRemove__return);


        }
        {
        System.out.println("Invoking catalogProductLinkRemove...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductLinkRemoveRequestParam _catalogProductLinkRemove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductLinkRemoveResponseParam _catalogProductLinkRemove__return = port.catalogProductLinkRemove(_catalogProductLinkRemove_parameters);
        System.out.println("catalogProductLinkRemove.result=" + _catalogProductLinkRemove__return);


        }
        {
        System.out.println("Invoking shoppingCartLicense...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartLicenseRequestParam _shoppingCartLicense_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartLicenseResponseParam _shoppingCartLicense__return = port.shoppingCartLicense(_shoppingCartLicense_parameters);
        System.out.println("shoppingCartLicense.result=" + _shoppingCartLicense__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetList...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetListRequestParam _catalogProductAttributeSetList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeSetListResponseParam _catalogProductAttributeSetList__return = port.catalogProductAttributeSetList(_catalogProductAttributeSetList_parameters);
        System.out.println("catalogProductAttributeSetList.result=" + _catalogProductAttributeSetList__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionValueRemove...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionValueRemoveRequestParam _catalogProductCustomOptionValueRemove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductCustomOptionValueRemoveResponseParam _catalogProductCustomOptionValueRemove__return = port.catalogProductCustomOptionValueRemove(_catalogProductCustomOptionValueRemove_parameters);
        System.out.println("catalogProductCustomOptionValueRemove.result=" + _catalogProductCustomOptionValueRemove__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceVoid...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceVoidRequestParam _salesOrderInvoiceVoid_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceVoidResponseParam _salesOrderInvoiceVoid__return = port.salesOrderInvoiceVoid(_salesOrderInvoiceVoid_parameters);
        System.out.println("salesOrderInvoiceVoid.result=" + _salesOrderInvoiceVoid__return);


        }
        {
        System.out.println("Invoking catalogCategoryMove...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryMoveRequestParam _catalogCategoryMove_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryMoveResponseParam _catalogCategoryMove__return = port.catalogCategoryMove(_catalogCategoryMove_parameters);
        System.out.println("catalogCategoryMove.result=" + _catalogCategoryMove__return);


        }
        {
        System.out.println("Invoking salesOrderAddComment...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderAddCommentRequestParam _salesOrderAddComment_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderAddCommentResponseParam _salesOrderAddComment__return = port.salesOrderAddComment(_salesOrderAddComment_parameters);
        System.out.println("salesOrderAddComment.result=" + _salesOrderAddComment__return);


        }
        {
        System.out.println("Invoking salesOrderHold...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderHoldRequestParam _salesOrderHold_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderHoldResponseParam _salesOrderHold__return = port.salesOrderHold(_salesOrderHold_parameters);
        System.out.println("salesOrderHold.result=" + _salesOrderHold__return);


        }
        {
        System.out.println("Invoking shoppingCartPaymentMethod...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartPaymentMethodRequestParam _shoppingCartPaymentMethod_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartPaymentMethodResponseParam _shoppingCartPaymentMethod__return = port.shoppingCartPaymentMethod(_shoppingCartPaymentMethod_parameters);
        System.out.println("shoppingCartPaymentMethod.result=" + _shoppingCartPaymentMethod__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceList...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceListRequestParam _salesOrderInvoiceList_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderInvoiceListResponseParam _salesOrderInvoiceList__return = port.salesOrderInvoiceList(_salesOrderInvoiceList_parameters);
        System.out.println("salesOrderInvoiceList.result=" + _salesOrderInvoiceList__return);


        }
        {
        System.out.println("Invoking catalogCategoryAssignedProducts...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryAssignedProductsRequestParam _catalogCategoryAssignedProducts_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryAssignedProductsResponseParam _catalogCategoryAssignedProducts__return = port.catalogCategoryAssignedProducts(_catalogCategoryAssignedProducts_parameters);
        System.out.println("catalogCategoryAssignedProducts.result=" + _catalogCategoryAssignedProducts__return);


        }
        {
        System.out.println("Invoking shoppingCartCouponAdd...");
        com.sitewhere.assetmodule.magento.ws.ShoppingCartCouponAddRequestParam _shoppingCartCouponAdd_parameters = null;
        com.sitewhere.assetmodule.magento.ws.ShoppingCartCouponAddResponseParam _shoppingCartCouponAdd__return = port.shoppingCartCouponAdd(_shoppingCartCouponAdd_parameters);
        System.out.println("shoppingCartCouponAdd.result=" + _shoppingCartCouponAdd__return);


        }
        {
        System.out.println("Invoking catalogProductLinkTypes...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductLinkTypesRequestParam _catalogProductLinkTypes_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductLinkTypesResponseParam _catalogProductLinkTypes__return = port.catalogProductLinkTypes(_catalogProductLinkTypes_parameters);
        System.out.println("catalogProductLinkTypes.result=" + _catalogProductLinkTypes__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentSendInfo...");
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentSendInfoRequestParam _salesOrderShipmentSendInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.SalesOrderShipmentSendInfoResponseParam _salesOrderShipmentSendInfo__return = port.salesOrderShipmentSendInfo(_salesOrderShipmentSendInfo_parameters);
        System.out.println("salesOrderShipmentSendInfo.result=" + _salesOrderShipmentSendInfo__return);


        }
        {
        System.out.println("Invoking catalogCategoryInfo...");
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryInfoRequestParam _catalogCategoryInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogCategoryInfoResponseParam _catalogCategoryInfo__return = port.catalogCategoryInfo(_catalogCategoryInfo_parameters);
        System.out.println("catalogCategoryInfo.result=" + _catalogCategoryInfo__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeTierPriceInfo...");
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeTierPriceInfoRequestParam _catalogProductAttributeTierPriceInfo_parameters = null;
        com.sitewhere.assetmodule.magento.ws.CatalogProductAttributeTierPriceInfoResponseParam _catalogProductAttributeTierPriceInfo__return = port.catalogProductAttributeTierPriceInfo(_catalogProductAttributeTierPriceInfo_parameters);
        System.out.println("catalogProductAttributeTierPriceInfo.result=" + _catalogProductAttributeTierPriceInfo__return);


        }

        System.exit(0);
    }

}
