// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sitewhere-common.proto

package com.sitewhere.grpc.model;

public final class CommonModel {
  private CommonModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GEntityInformationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sitewhere.grpc.model.GEntityInformation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 createdDate = 1;</code>
     */
    long getCreatedDate();

    /**
     * <code>string createdBy = 2;</code>
     */
    java.lang.String getCreatedBy();
    /**
     * <code>string createdBy = 2;</code>
     */
    com.google.protobuf.ByteString
        getCreatedByBytes();

    /**
     * <code>int64 updatedDate = 3;</code>
     */
    long getUpdatedDate();

    /**
     * <code>string updatedBy = 4;</code>
     */
    java.lang.String getUpdatedBy();
    /**
     * <code>string updatedBy = 4;</code>
     */
    com.google.protobuf.ByteString
        getUpdatedByBytes();

    /**
     * <code>bool deleted = 5;</code>
     */
    boolean getDeleted();
  }
  /**
   * <pre>
   * Common entity information.
   * </pre>
   *
   * Protobuf type {@code com.sitewhere.grpc.model.GEntityInformation}
   */
  public  static final class GEntityInformation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.sitewhere.grpc.model.GEntityInformation)
      GEntityInformationOrBuilder {
    // Use GEntityInformation.newBuilder() to construct.
    private GEntityInformation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GEntityInformation() {
      createdDate_ = 0L;
      createdBy_ = "";
      updatedDate_ = 0L;
      updatedBy_ = "";
      deleted_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GEntityInformation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              createdDate_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              createdBy_ = s;
              break;
            }
            case 24: {

              updatedDate_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              updatedBy_ = s;
              break;
            }
            case 40: {

              deleted_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sitewhere.grpc.model.CommonModel.internal_static_com_sitewhere_grpc_model_GEntityInformation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sitewhere.grpc.model.CommonModel.internal_static_com_sitewhere_grpc_model_GEntityInformation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sitewhere.grpc.model.CommonModel.GEntityInformation.class, com.sitewhere.grpc.model.CommonModel.GEntityInformation.Builder.class);
    }

    public static final int CREATEDDATE_FIELD_NUMBER = 1;
    private long createdDate_;
    /**
     * <code>int64 createdDate = 1;</code>
     */
    public long getCreatedDate() {
      return createdDate_;
    }

    public static final int CREATEDBY_FIELD_NUMBER = 2;
    private volatile java.lang.Object createdBy_;
    /**
     * <code>string createdBy = 2;</code>
     */
    public java.lang.String getCreatedBy() {
      java.lang.Object ref = createdBy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdBy_ = s;
        return s;
      }
    }
    /**
     * <code>string createdBy = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedByBytes() {
      java.lang.Object ref = createdBy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATEDDATE_FIELD_NUMBER = 3;
    private long updatedDate_;
    /**
     * <code>int64 updatedDate = 3;</code>
     */
    public long getUpdatedDate() {
      return updatedDate_;
    }

    public static final int UPDATEDBY_FIELD_NUMBER = 4;
    private volatile java.lang.Object updatedBy_;
    /**
     * <code>string updatedBy = 4;</code>
     */
    public java.lang.String getUpdatedBy() {
      java.lang.Object ref = updatedBy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updatedBy_ = s;
        return s;
      }
    }
    /**
     * <code>string updatedBy = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUpdatedByBytes() {
      java.lang.Object ref = updatedBy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updatedBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELETED_FIELD_NUMBER = 5;
    private boolean deleted_;
    /**
     * <code>bool deleted = 5;</code>
     */
    public boolean getDeleted() {
      return deleted_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (createdDate_ != 0L) {
        output.writeInt64(1, createdDate_);
      }
      if (!getCreatedByBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, createdBy_);
      }
      if (updatedDate_ != 0L) {
        output.writeInt64(3, updatedDate_);
      }
      if (!getUpdatedByBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, updatedBy_);
      }
      if (deleted_ != false) {
        output.writeBool(5, deleted_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (createdDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, createdDate_);
      }
      if (!getCreatedByBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, createdBy_);
      }
      if (updatedDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, updatedDate_);
      }
      if (!getUpdatedByBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, updatedBy_);
      }
      if (deleted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, deleted_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sitewhere.grpc.model.CommonModel.GEntityInformation)) {
        return super.equals(obj);
      }
      com.sitewhere.grpc.model.CommonModel.GEntityInformation other = (com.sitewhere.grpc.model.CommonModel.GEntityInformation) obj;

      boolean result = true;
      result = result && (getCreatedDate()
          == other.getCreatedDate());
      result = result && getCreatedBy()
          .equals(other.getCreatedBy());
      result = result && (getUpdatedDate()
          == other.getUpdatedDate());
      result = result && getUpdatedBy()
          .equals(other.getUpdatedBy());
      result = result && (getDeleted()
          == other.getDeleted());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CREATEDDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreatedDate());
      hash = (37 * hash) + CREATEDBY_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedBy().hashCode();
      hash = (37 * hash) + UPDATEDDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdatedDate());
      hash = (37 * hash) + UPDATEDBY_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedBy().hashCode();
      hash = (37 * hash) + DELETED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDeleted());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sitewhere.grpc.model.CommonModel.GEntityInformation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Common entity information.
     * </pre>
     *
     * Protobuf type {@code com.sitewhere.grpc.model.GEntityInformation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sitewhere.grpc.model.GEntityInformation)
        com.sitewhere.grpc.model.CommonModel.GEntityInformationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sitewhere.grpc.model.CommonModel.internal_static_com_sitewhere_grpc_model_GEntityInformation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sitewhere.grpc.model.CommonModel.internal_static_com_sitewhere_grpc_model_GEntityInformation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sitewhere.grpc.model.CommonModel.GEntityInformation.class, com.sitewhere.grpc.model.CommonModel.GEntityInformation.Builder.class);
      }

      // Construct using com.sitewhere.grpc.model.CommonModel.GEntityInformation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        createdDate_ = 0L;

        createdBy_ = "";

        updatedDate_ = 0L;

        updatedBy_ = "";

        deleted_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sitewhere.grpc.model.CommonModel.internal_static_com_sitewhere_grpc_model_GEntityInformation_descriptor;
      }

      public com.sitewhere.grpc.model.CommonModel.GEntityInformation getDefaultInstanceForType() {
        return com.sitewhere.grpc.model.CommonModel.GEntityInformation.getDefaultInstance();
      }

      public com.sitewhere.grpc.model.CommonModel.GEntityInformation build() {
        com.sitewhere.grpc.model.CommonModel.GEntityInformation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sitewhere.grpc.model.CommonModel.GEntityInformation buildPartial() {
        com.sitewhere.grpc.model.CommonModel.GEntityInformation result = new com.sitewhere.grpc.model.CommonModel.GEntityInformation(this);
        result.createdDate_ = createdDate_;
        result.createdBy_ = createdBy_;
        result.updatedDate_ = updatedDate_;
        result.updatedBy_ = updatedBy_;
        result.deleted_ = deleted_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sitewhere.grpc.model.CommonModel.GEntityInformation) {
          return mergeFrom((com.sitewhere.grpc.model.CommonModel.GEntityInformation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sitewhere.grpc.model.CommonModel.GEntityInformation other) {
        if (other == com.sitewhere.grpc.model.CommonModel.GEntityInformation.getDefaultInstance()) return this;
        if (other.getCreatedDate() != 0L) {
          setCreatedDate(other.getCreatedDate());
        }
        if (!other.getCreatedBy().isEmpty()) {
          createdBy_ = other.createdBy_;
          onChanged();
        }
        if (other.getUpdatedDate() != 0L) {
          setUpdatedDate(other.getUpdatedDate());
        }
        if (!other.getUpdatedBy().isEmpty()) {
          updatedBy_ = other.updatedBy_;
          onChanged();
        }
        if (other.getDeleted() != false) {
          setDeleted(other.getDeleted());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sitewhere.grpc.model.CommonModel.GEntityInformation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sitewhere.grpc.model.CommonModel.GEntityInformation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long createdDate_ ;
      /**
       * <code>int64 createdDate = 1;</code>
       */
      public long getCreatedDate() {
        return createdDate_;
      }
      /**
       * <code>int64 createdDate = 1;</code>
       */
      public Builder setCreatedDate(long value) {
        
        createdDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 createdDate = 1;</code>
       */
      public Builder clearCreatedDate() {
        
        createdDate_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object createdBy_ = "";
      /**
       * <code>string createdBy = 2;</code>
       */
      public java.lang.String getCreatedBy() {
        java.lang.Object ref = createdBy_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          createdBy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string createdBy = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCreatedByBytes() {
        java.lang.Object ref = createdBy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createdBy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string createdBy = 2;</code>
       */
      public Builder setCreatedBy(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createdBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string createdBy = 2;</code>
       */
      public Builder clearCreatedBy() {
        
        createdBy_ = getDefaultInstance().getCreatedBy();
        onChanged();
        return this;
      }
      /**
       * <code>string createdBy = 2;</code>
       */
      public Builder setCreatedByBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createdBy_ = value;
        onChanged();
        return this;
      }

      private long updatedDate_ ;
      /**
       * <code>int64 updatedDate = 3;</code>
       */
      public long getUpdatedDate() {
        return updatedDate_;
      }
      /**
       * <code>int64 updatedDate = 3;</code>
       */
      public Builder setUpdatedDate(long value) {
        
        updatedDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 updatedDate = 3;</code>
       */
      public Builder clearUpdatedDate() {
        
        updatedDate_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object updatedBy_ = "";
      /**
       * <code>string updatedBy = 4;</code>
       */
      public java.lang.String getUpdatedBy() {
        java.lang.Object ref = updatedBy_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          updatedBy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string updatedBy = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUpdatedByBytes() {
        java.lang.Object ref = updatedBy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          updatedBy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string updatedBy = 4;</code>
       */
      public Builder setUpdatedBy(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updatedBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string updatedBy = 4;</code>
       */
      public Builder clearUpdatedBy() {
        
        updatedBy_ = getDefaultInstance().getUpdatedBy();
        onChanged();
        return this;
      }
      /**
       * <code>string updatedBy = 4;</code>
       */
      public Builder setUpdatedByBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updatedBy_ = value;
        onChanged();
        return this;
      }

      private boolean deleted_ ;
      /**
       * <code>bool deleted = 5;</code>
       */
      public boolean getDeleted() {
        return deleted_;
      }
      /**
       * <code>bool deleted = 5;</code>
       */
      public Builder setDeleted(boolean value) {
        
        deleted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool deleted = 5;</code>
       */
      public Builder clearDeleted() {
        
        deleted_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.sitewhere.grpc.model.GEntityInformation)
    }

    // @@protoc_insertion_point(class_scope:com.sitewhere.grpc.model.GEntityInformation)
    private static final com.sitewhere.grpc.model.CommonModel.GEntityInformation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sitewhere.grpc.model.CommonModel.GEntityInformation();
    }

    public static com.sitewhere.grpc.model.CommonModel.GEntityInformation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GEntityInformation>
        PARSER = new com.google.protobuf.AbstractParser<GEntityInformation>() {
      public GEntityInformation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GEntityInformation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GEntityInformation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GEntityInformation> getParserForType() {
      return PARSER;
    }

    public com.sitewhere.grpc.model.CommonModel.GEntityInformation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sitewhere_grpc_model_GEntityInformation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sitewhere_grpc_model_GEntityInformation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026sitewhere-common.proto\022\030com.sitewhere." +
      "grpc.model\"u\n\022GEntityInformation\022\023\n\013crea" +
      "tedDate\030\001 \001(\003\022\021\n\tcreatedBy\030\002 \001(\t\022\023\n\013upda" +
      "tedDate\030\003 \001(\003\022\021\n\tupdatedBy\030\004 \001(\t\022\017\n\007dele" +
      "ted\030\005 \001(\010B\rB\013CommonModelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_sitewhere_grpc_model_GEntityInformation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sitewhere_grpc_model_GEntityInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sitewhere_grpc_model_GEntityInformation_descriptor,
        new java.lang.String[] { "CreatedDate", "CreatedBy", "UpdatedDate", "UpdatedBy", "Deleted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
