// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tenant-management.proto

package com.sitewhere.grpc.model;

public final class TenantServices {
  private TenantServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027tenant-management.proto\022\030com.sitewhere" +
      ".grpc.model\032\022tenant-model.proto2w\n\020Tenan" +
      "tManagement\022c\n\014CreateTenant\022..com.sitewh" +
      "ere.grpc.model.GTenantCreateRequest\032!.co" +
      "m.sitewhere.grpc.model.GTenant\"\000B,\n\030com." +
      "sitewhere.grpc.modelB\016TenantServicesP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sitewhere.grpc.model.TenantModel.getDescriptor(),
        }, assigner);
    com.sitewhere.grpc.model.TenantModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
