
package com.sitewhere.asset.modules.wso2.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Aug 05 14:07:17 EDT 2015
 * Generated source version: 2.3.1
 * 
 */

public final class RemoteUserStoreManagerServicePortType_RemoteUserStoreManagerServiceHttpsEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ws.um.carbon.wso2.org", "RemoteUserStoreManagerService");

    private RemoteUserStoreManagerServicePortType_RemoteUserStoreManagerServiceHttpsEndpoint_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = RemoteUserStoreManagerService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RemoteUserStoreManagerService ss = new RemoteUserStoreManagerService(wsdlURL, SERVICE_NAME);
        RemoteUserStoreManagerServicePortType port = ss.getRemoteUserStoreManagerServiceHttpsEndpoint();  
        
        {
        System.out.println("Invoking isExistingRole...");
        java.lang.String _isExistingRole_roleName = "";
        try {
            java.lang.Boolean _isExistingRole__return = port.isExistingRole(_isExistingRole_roleName);
            System.out.println("isExistingRole.result=" + _isExistingRole__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking setUserClaimValues...");
        java.lang.String _setUserClaimValues_userName = "";
        java.util.List<com.sitewhere.asset.modules.wso2.ws.ClaimValue> _setUserClaimValues_claims = null;
        java.lang.String _setUserClaimValues_profileName = "";
        port.setUserClaimValues(_setUserClaimValues_userName, _setUserClaimValues_claims, _setUserClaimValues_profileName);


        }
        {
        System.out.println("Invoking getUserClaimValuesForClaims...");
        java.lang.String _getUserClaimValuesForClaims_userName = "";
        java.util.List<java.lang.String> _getUserClaimValuesForClaims_claims = null;
        java.lang.String _getUserClaimValuesForClaims_profileName = "";
        try {
            java.util.List<com.sitewhere.asset.modules.wso2.ws.ClaimValue> _getUserClaimValuesForClaims__return = port.getUserClaimValuesForClaims(_getUserClaimValuesForClaims_userName, _getUserClaimValuesForClaims_claims, _getUserClaimValuesForClaims_profileName);
            System.out.println("getUserClaimValuesForClaims.result=" + _getUserClaimValuesForClaims__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteUser...");
        java.lang.String _deleteUser_userName = "";
        port.deleteUser(_deleteUser_userName);


        }
        {
        System.out.println("Invoking updateRoleListOfUser...");
        java.lang.String _updateRoleListOfUser_userName = "";
        java.util.List<java.lang.String> _updateRoleListOfUser_deletedRoles = null;
        java.util.List<java.lang.String> _updateRoleListOfUser_newRoles = null;
        port.updateRoleListOfUser(_updateRoleListOfUser_userName, _updateRoleListOfUser_deletedRoles, _updateRoleListOfUser_newRoles);


        }
        {
        System.out.println("Invoking addRole...");
        java.lang.String _addRole_roleName = "";
        java.util.List<java.lang.String> _addRole_userList = null;
        java.util.List<com.sitewhere.asset.modules.wso2.ws.PermissionDTO> _addRole_permissions = null;
        port.addRole(_addRole_roleName, _addRole_userList, _addRole_permissions);


        }
        {
        System.out.println("Invoking isExistingUser...");
        java.lang.String _isExistingUser_userName = "";
        try {
            java.lang.Boolean _isExistingUser__return = port.isExistingUser(_isExistingUser_userName);
            System.out.println("isExistingUser.result=" + _isExistingUser__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addUser...");
        java.lang.String _addUser_userName = "";
        java.lang.String _addUser_credential = "";
        java.util.List<java.lang.String> _addUser_roleList = null;
        java.util.List<com.sitewhere.asset.modules.wso2.ws.ClaimValue> _addUser_claims = null;
        java.lang.String _addUser_profileName = "";
        java.lang.Boolean _addUser_requirePasswordChange = null;
        port.addUser(_addUser_userName, _addUser_credential, _addUser_roleList, _addUser_claims, _addUser_profileName, _addUser_requirePasswordChange);


        }
        {
        System.out.println("Invoking getAllProfileNames...");
        try {
            java.util.List<java.lang.String> _getAllProfileNames__return = port.getAllProfileNames();
            System.out.println("getAllProfileNames.result=" + _getAllProfileNames__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRoleNames...");
        try {
            java.util.List<java.lang.String> _getRoleNames__return = port.getRoleNames();
            System.out.println("getRoleNames.result=" + _getRoleNames__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUserList...");
        java.lang.String _getUserList_claimUri = "";
        java.lang.String _getUserList_claimValue = "";
        java.lang.String _getUserList_profile = "";
        try {
            java.util.List<java.lang.String> _getUserList__return = port.getUserList(_getUserList_claimUri, _getUserList_claimValue, _getUserList_profile);
            System.out.println("getUserList.result=" + _getUserList__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteUserClaimValue...");
        java.lang.String _deleteUserClaimValue_userName = "";
        java.lang.String _deleteUserClaimValue_claimURI = "";
        java.lang.String _deleteUserClaimValue_profileName = "";
        port.deleteUserClaimValue(_deleteUserClaimValue_userName, _deleteUserClaimValue_claimURI, _deleteUserClaimValue_profileName);


        }
        {
        System.out.println("Invoking getProfileNames...");
        java.lang.String _getProfileNames_userName = "";
        try {
            java.util.List<java.lang.String> _getProfileNames__return = port.getProfileNames(_getProfileNames_userName);
            System.out.println("getProfileNames.result=" + _getProfileNames__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateRoleName...");
        java.lang.String _updateRoleName_roleName = "";
        java.lang.String _updateRoleName_newRoleName = "";
        port.updateRoleName(_updateRoleName_roleName, _updateRoleName_newRoleName);


        }
        {
        System.out.println("Invoking updateUserListOfRole...");
        java.lang.String _updateUserListOfRole_roleName = "";
        java.util.List<java.lang.String> _updateUserListOfRole_deletedUsers = null;
        java.util.List<java.lang.String> _updateUserListOfRole_newUsers = null;
        port.updateUserListOfRole(_updateUserListOfRole_roleName, _updateUserListOfRole_deletedUsers, _updateUserListOfRole_newUsers);


        }
        {
        System.out.println("Invoking addUserClaimValue...");
        java.lang.String _addUserClaimValue_userName = "";
        java.lang.String _addUserClaimValue_claimURI = "";
        java.lang.String _addUserClaimValue_claimValue = "";
        java.lang.String _addUserClaimValue_profileName = "";
        port.addUserClaimValue(_addUserClaimValue_userName, _addUserClaimValue_claimURI, _addUserClaimValue_claimValue, _addUserClaimValue_profileName);


        }
        {
        System.out.println("Invoking getHybridRoles...");
        try {
            java.util.List<java.lang.String> _getHybridRoles__return = port.getHybridRoles();
            System.out.println("getHybridRoles.result=" + _getHybridRoles__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteUserClaimValues...");
        java.lang.String _deleteUserClaimValues_userName = "";
        java.util.List<java.lang.String> _deleteUserClaimValues_claims = null;
        java.lang.String _deleteUserClaimValues_profileName = "";
        port.deleteUserClaimValues(_deleteUserClaimValues_userName, _deleteUserClaimValues_claims, _deleteUserClaimValues_profileName);


        }
        {
        System.out.println("Invoking authenticate...");
        java.lang.String _authenticate_userName = "";
        java.lang.String _authenticate_credential = "";
        try {
            java.lang.Boolean _authenticate__return = port.authenticate(_authenticate_userName, _authenticate_credential);
            System.out.println("authenticate.result=" + _authenticate__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUserClaimValues...");
        java.lang.String _getUserClaimValues_userName = "";
        java.lang.String _getUserClaimValues_profileName = "";
        try {
            java.util.List<com.sitewhere.asset.modules.wso2.ws.ClaimDTO> _getUserClaimValues__return = port.getUserClaimValues(_getUserClaimValues_userName, _getUserClaimValues_profileName);
            System.out.println("getUserClaimValues.result=" + _getUserClaimValues__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUserId...");
        java.lang.String _getUserId_username = "";
        try {
            java.lang.Integer _getUserId__return = port.getUserId(_getUserId_username);
            System.out.println("getUserId.result=" + _getUserId__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteRole...");
        java.lang.String _deleteRole_roleName = "";
        port.deleteRole(_deleteRole_roleName);


        }
        {
        System.out.println("Invoking getUserListOfRole...");
        java.lang.String _getUserListOfRole_roleName = "";
        try {
            java.util.List<java.lang.String> _getUserListOfRole__return = port.getUserListOfRole(_getUserListOfRole_roleName);
            System.out.println("getUserListOfRole.result=" + _getUserListOfRole__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRoleListOfUser...");
        java.lang.String _getRoleListOfUser_userName = "";
        try {
            java.util.List<java.lang.String> _getRoleListOfUser__return = port.getRoleListOfUser(_getRoleListOfUser_userName);
            System.out.println("getRoleListOfUser.result=" + _getRoleListOfUser__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addUserClaimValues...");
        java.lang.String _addUserClaimValues_userName = "";
        java.util.List<com.sitewhere.asset.modules.wso2.ws.ClaimValue> _addUserClaimValues_claims = null;
        java.lang.String _addUserClaimValues_profileName = "";
        port.addUserClaimValues(_addUserClaimValues_userName, _addUserClaimValues_claims, _addUserClaimValues_profileName);


        }
        {
        System.out.println("Invoking updateCredential...");
        java.lang.String _updateCredential_userName = "";
        java.lang.String _updateCredential_newCredential = "";
        java.lang.String _updateCredential_oldCredential = "";
        port.updateCredential(_updateCredential_userName, _updateCredential_newCredential, _updateCredential_oldCredential);


        }
        {
        System.out.println("Invoking setUserClaimValue...");
        java.lang.String _setUserClaimValue_userName = "";
        java.lang.String _setUserClaimValue_claimURI = "";
        java.lang.String _setUserClaimValue_claimValue = "";
        java.lang.String _setUserClaimValue_profileName = "";
        port.setUserClaimValue(_setUserClaimValue_userName, _setUserClaimValue_claimURI, _setUserClaimValue_claimValue, _setUserClaimValue_profileName);


        }
        {
        System.out.println("Invoking getProperties...");
        com.sitewhere.asset.modules.wso2.ws.AX2604Tenant _getProperties_tenant = null;
        try {
            java.util.List<com.sitewhere.asset.modules.wso2.ws.ArrayOfString> _getProperties__return = port.getProperties(_getProperties_tenant);
            System.out.println("getProperties.result=" + _getProperties__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking isReadOnly...");
        try {
            java.lang.Boolean _isReadOnly__return = port.isReadOnly();
            System.out.println("isReadOnly.result=" + _isReadOnly__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUserClaimValue...");
        java.lang.String _getUserClaimValue_userName = "";
        java.lang.String _getUserClaimValue_claim = "";
        java.lang.String _getUserClaimValue_profileName = "";
        try {
            java.lang.String _getUserClaimValue__return = port.getUserClaimValue(_getUserClaimValue_userName, _getUserClaimValue_claim, _getUserClaimValue_profileName);
            System.out.println("getUserClaimValue.result=" + _getUserClaimValue__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTenantIdofUser...");
        java.lang.String _getTenantIdofUser_username = "";
        try {
            java.lang.Integer _getTenantIdofUser__return = port.getTenantIdofUser(_getTenantIdofUser_username);
            System.out.println("getTenantIdofUser.result=" + _getTenantIdofUser__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking listUsers...");
        java.lang.String _listUsers_filter = "";
        java.lang.Integer _listUsers_maxItemLimit = null;
        try {
            java.util.List<java.lang.String> _listUsers__return = port.listUsers(_listUsers_filter, _listUsers_maxItemLimit);
            System.out.println("listUsers.result=" + _listUsers__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPasswordExpirationTime...");
        java.lang.String _getPasswordExpirationTime_username = "";
        try {
            java.lang.Long _getPasswordExpirationTime__return = port.getPasswordExpirationTime(_getPasswordExpirationTime_username);
            System.out.println("getPasswordExpirationTime.result=" + _getPasswordExpirationTime__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateCredentialByAdmin...");
        java.lang.String _updateCredentialByAdmin_userName = "";
        java.lang.String _updateCredentialByAdmin_newCredential = "";
        port.updateCredentialByAdmin(_updateCredentialByAdmin_userName, _updateCredentialByAdmin_newCredential);


        }
        {
        System.out.println("Invoking getTenantId...");
        try {
            java.lang.Integer _getTenantId__return = port.getTenantId();
            System.out.println("getTenantId.result=" + _getTenantId__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) { 
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
